### ISSUE TITLE
Unify KMeans prediction formats

### ISSUE THREAD

**Issue by mdymczyk** [h2oai/h2o4gpu#103]
Below stuff was fixed but KMeans still requires transforms and centroids to preserve format.

~~`model.labels_` and `model.predict(X)` seem to return the same results but sometimes in different orders (`c` style vs `r` style).~~
```
>>> import numpy as np
>>> from h2o4gpu import KMeans
>>> X = np.array([[1.,0.], [2.,3.], [1.,2.], [2.,4.]])
>>> model = KMeans(n_clusters=2).fit(X)
>>> model.labels_
array([1, 1, 0, 0], dtype=int32)
>>> model.predict(X)
array([1, 0, 1, 0], dtype=int32)
```

~~Also there are some discrepancies when passing in `int` values:~~
```
>>> import numpy as np
>>> from h2o4gpu import KMeans
>>> X = np.array([[1,0], [2,3], [1,2], [2,4]])
>>> model = KMeans(n_clusters=2).fit(X)
>>> model.labels_
array([1, 1, 0, 0], dtype=int32)
>>> model.predict(X)
array([1, 1, 1, 0], dtype=int32)
```

~~Also running with multiple GPUs seems to change the order of predictions.~~

**Comment by sh1ng** [comment]
There're a few tests for that.
