### ISSUE TITLE
Add C++/CUDA unit testing frameworks 

### ISSUE THREAD

**Issue by mdymczyk** [h2oai/h2o4gpu#152]
Currently 0 tests for our C++/CUDA code. Writing short unit tests can often be faster and easier than adding prints in code. Also we should try not to leave debug code in the codebase - if everyone does that we'll bloat it too much. Small unit tests can do the same job in a more readable (and repeatable) way.

**Comment by RemusRomulus** [comment]
How are you writing unit tests for your CUDA code?

**Comment by mdymczyk** [comment]
@RemusRomulus we currently have a very basic set of few tests built and run via Makefile (https://github.com/h2oai/h2o4gpu/blob/master/tests/cpp/Makefile). We are using GoogleTest. Need to add more and run them as part of the build process, still.
