### ISSUE TITLE
Add builds for different Python versions/OSs/CUDA/etc.

### ISSUE THREAD

**Issue by mdymczyk** [h2oai/h2o4gpu#154]
Currently our package is "python version bound" b/c of ScikitLearn (since they are using Cython).

Seems like quite a few people are still using Python 3.5, we might need to add a build step also for that Python version. Also we'll need a Windows CI machine if we want to generate whl files for Windows.

Lets start with adding builds for Python 3.5.

**Comment by pseudotensor** [comment]
we will add to jenkins conda and other python versions and other cuda versions

**Comment by pseudotensor** [comment]
See also: https://github.com/dmlc/xgboost/blob/master/Jenkinsfile

**Comment by mdymczyk** [comment]
Closing in favor of #355 and the windows issue.
