### ISSUE TITLE
KMeans extremely slow for low k

### ISSUE THREAD

**Issue by mdymczyk** [h2oai/h2o4gpu#177]
```
from h2o4gpu import KMeans as h2oKMeans
from sklearn.cluster import KMeans as skKMeans
from sklearn.datasets.samples_generator import make_blobs
from sklearn.metrics.cluster import v_measure_score

n_samples = 1000000
centers = 16
# Generate random 'center' centroids and 'n_samples' samples around them
X, true_labels = make_blobs(n_samples=n_samples, centers=centers,
                             cluster_std=1., random_state=42)

kmeans_h2o = h2oKMeans(n_gpus=1, n_clusters=centers, max_iter=5, tol=1e-8)
kmeans_h2o.fit(X)
```

Fit takes around `Wall time: 3.84 s`. If we change centers to `17` we get `Wall time: 543 ms`.

The difference clearly starts to show at around `75000` rows.

**Comment by pseudotensor** [comment]
example of why slow for small k: kernels are not well-tuned for small k. they end up using very few cores and threads.

**Comment by mdymczyk** [comment]
The issue is `cublasSgemm` call in `kmeans_labels.cu#calculate_distances`. Lost the link but read on the NVidia forum that none of the dimensions should be less than 16 when using that method (preferably 32).

We need to add a different way of calculating matrix-matrix product for matrices with smaller dimensions.

**Comment by pseudotensor** [comment]
Ok, no problem then.  I liked @RAMitchell 's simple way of just doing vector matrix multiplication instead.  What he suggested is very easy to do stages: 1) Do sequential v-m ops (e.g. cublasSgemv) for each small k<32.  2) If that works fine, you can write your own kernel that takes streams and do them in parallel.  I don't think the cublasSgemv takes streams -- ask Rory what to do as well.

**Comment by mdymczyk** [comment]
Performance has already improved by quite a lot. If more performance improvements are required we can further tweak it.
