### ISSUE TITLE
Invalid Predictions when using separate Training+Validation and Test datasets 

### ISSUE THREAD

**Issue by wamsiv** [h2oai/h2o4gpu#196]
### Environment (for bugs)

- **OS platform, distribution and version (e.g. Linux Ubuntu 16.04)**:  _CentOS Linux release 7.3.1611 (Core)_
- **Installed from (source or binary)**: _Binary_
- **Version**: _ 0.0.3_
- **Python version (optional)**: _3.5.3_
- **CUDA/cuDNN version**: _8.0.61_
- **GPU model (optional)**: 
- **CPU model**:
- **RAM available**:

Please refer to google on how to obtain the above on your platform.

### Description

1. 
`fit_ptr` method gets error out(Kernel Dies) if Null or zero pointer values are provided for `c` and `d`. Currently, the method looks like: `enet.fit_ptr(mTrain, n, mValid, precision, None, a=a, b=b,c=c,d=d,e=e ,source_dev=0)`

Step to reproduce:
Replace c and d with either `c=c_void_p(None), d=c_void_p(None)` or `c=c_void_p(0), d=c_void_p(0)` in the above fit_ptr method.

2. 
`predict_ptr` method predicts out all the values as zero or negative if different pointer values are used apart from original `c and d` for predictions.

steps to reproduce:

- Pick a data set and divide it into training and validation (eg ratio 70:30), make matrices out of it and form `a,b,c,d,e` 

- From the same dataset pick another subset of data, make matrix of it and call it g. `g`: make has same order of feature columns as  `c` has.

-  Now use `enet.fit_ptr(mTrain, n, mValid, precision, None, a=a, b=b,c=c,d=d,e=e,source_dev=0)` to train the model and compare the predictions between `enet.predict_ptr(c)` and `enet.predict_ptr(g)`

-  The second method will have predictions as all zero as compared to the first where we use `c`

-  Please refer to the notebook for more details: https://gist.github.com/wamsiv/14665fc500161fb837f4ff1d8528a29f

**Comment by pseudotensor** [comment]
problem was different colums for train and test due to one hot encoding.  Could allow user to pass in rows and cols even for pointer case to have it check for user that they have wrong input.
