### ISSUE TITLE
Try to remove PyFPE dependency and tag wheel properly

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#201]
@sklam

The problem is that the wheel is built from a CPython build with the `--with-fpectl` flag.  It changes the ABI for CPython.  For portable ABI, it should not use fpectl.  See https://www.python.org/dev/peps/pep-0513/#fpectl-builds-vs-no-fpectl-builds
Python.org
PEP 513 -- A Platform Tag for Portable Linux Built Distributions
The official home of the Python Programming Language

You can check the wheel with `auditwheel`

 ```$ auditwheel show h2o4gpu-0.0.4-py36-none-any.whl

h2o4gpu-0.0.4-py36-none-any.whl is consistent with the following
platform tag: "linux_x86_64".

This wheel uses the PyFPE_jbuf function, which is not compatible with
the manylinux1 tag. (see
https://www.python.org/dev/peps/pep-0513/#fpectl-builds-vs-no-fpectl-
builds)
```
sklam [1:14 PM] 
I think it's coming from one of the sharedlib in h2o4gpu.  The error points to `h2o4gpu/utils/sparsefuncs_fast.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf` (edited)

**Comment by pseudotensor** [comment]
See also: https://github.com/scikit-learn/scikit-learn/issues/7542#issuecomment-250908129

**Comment by pseudotensor** [comment]
It looks like jenkins build is clean of fpectl now. #249 

jon@mr-dl10:~$ auditwheel show h2o4gpu-0.0.4-py36-none-any.whl
WARNING:auditwheel.lddtree:[Errno 21] Is a directory: '/usr/local/cuda/lib64/'

h2o4gpu-0.0.4-py36-none-any.whl is consistent with the following
platform tag: "linux_x86_64".

The wheel references external versioned symbols in these system-
provided shared libraries: libc.so.6 with versions {'GLIBC_2.4',
'GLIBC_2.2.5', 'GLIBC_2.14', 'GLIBC_2.3.4'}, libgcc_s.so.1 with
versions {'GCC_3.0'}, libstdc++.so.6 with versions {'CXXABI_1.3',
'GLIBCXX_3.4', 'GLIBCXX_3.4.21'}, libm.so.6 with versions
{'GLIBC_2.2.5'}

This constrains the platform tag to "linux_x86_64". In order to
achieve a more compatible tag, you would to recompile a new wheel from
source on a system with earlier versions of these libraries, such as
CentOS 5.

**Comment by pseudotensor** [comment]
Note that cannot repair wheel to make it manylinux compatible, so really shouldn't have none-any and should be at least linux_x86_64.  But hope to remove scikit-learn dependency that really makes it cpython dependent.

jon@mr-dl10:~$ auditwheel repair h2o4gpu-0.0.4-py36-none-any.whl
Repairing h2o4gpu-0.0.4-py36-none-any.whl
WARNING:auditwheel.lddtree:[Errno 21] Is a directory: '/usr/local/cuda/lib64/'
usage: auditwheel [-h] [-V] [-v] command ...
auditwheel: error: cannot repair "h2o4gpu-0.0.4-py36-none-any.whl" to "manylinux1_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.
jon@mr-dl10:~$

**Comment by mdymczyk** [comment]
@pseudotensor yes removing that dep would be a great idea - making our own package cythonized is one thing but another thing is we're now relying only on a single Scikit version. It would be good for us to just say "h2o4gpu version X handles Scikit version ZZZ - YYY" instead. Do you already have any ideas how to remove that dep or do we need to do some research?

**Comment by pseudotensor** [comment]
Yes, it's easy, just have to get time.  It just involves removing the submodule and all scripts for preparing sklearn, then when we import an sklearn module for our backup method, we only import the very specific class as a different named class and use that (e..g. from sklearn.cluster.kmeans_ import KMeans as KMeans_sklearn).  Should be fine, but may hit snag.

**Comment by memory-yancy** [comment]
@pseudotensor  Nice finding. I installed it and import h2o4gpu will produce similar errors, I got whl file from @mdymczyk  Bleeding edge(README.md master branch).  Hope fix it. 
```
ImportError: /root/anaconda2/envs/new/lib/python3.6/site-packages/h2o4gpu/utils/sparsefuncs_fast.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
```

**Comment by pseudotensor** [comment]
Hi @memory-yancy I can't quite follow you.   Can you try the latest bleeding edge wheel?

**Comment by memory-yancy** [comment]
@pseudotensor Sorry sincerely for replying latter. 
OK, since previous issue, I got answer and then I follow @mdymczyk suggestion for using new `h2o4gpu wheel file` in README.md file, but I will produce a error when I installed it and use it.
```
(wheel_1) [root@sd002024 ~]$ md5sum ~/github/new-whl-h2o4gpu/h2o4gpu-0.0.4-py36-none-any.whl 
e35607c0756002fcc37cdfb5ca8ecc1e  /root/github/new-whl-h2o4gpu/h2o4gpu-0.0.4-py36-none-any.whl
```
I use `conda` create a clean virtual env by `conda create --name wheel_1 python=3.6`, and then I use pip to install `h2o4gpu-XXXXXX.whl` file and it's ok.
```
# since will produce a lots dependency output installing info, I filter it and will judge it,
(wheel_1) [root@sd002024 ~]$ pip install ~/github/new-whl-h2o4gpu/h2o4gpu-0.0.4-py36-none-any.whl > /dev/null                                                                                                                             
(wheel_1) [root@sd002024 ~]$ echo $?
0
```
Then, I am ready to use, but:
```
(wheel_1) [root@sd002024 ~]$ python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 27 2017, 19:41:01) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h2o4gpu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda2/envs/wheel_1/lib/python3.6/site-packages/h2o4gpu/__init__.py", line 11, in <module>
    from .solvers.pogs import Pogs
  File "/root/anaconda2/envs/wheel_1/lib/python3.6/site-packages/h2o4gpu/solvers/__init__.py", line 8, in <module>
    from ..solvers.elastic_net import ElasticNetH2O
  File "/root/anaconda2/envs/wheel_1/lib/python3.6/site-packages/h2o4gpu/solvers/elastic_net.py", line 14, in <module>
    from h2o4gpu.linear_model import coordinate_descent as sk
  File "/root/anaconda2/envs/wheel_1/lib/python3.6/site-packages/h2o4gpu/linear_model/__init__.py", line 12, in <module>
    from .base import LinearRegressionSklearn
  File "/root/anaconda2/envs/wheel_1/lib/python3.6/site-packages/h2o4gpu/linear_model/base.py", line 32, in <module>
    from ..utils.extmath import safe_sparse_dot
  File "/root/anaconda2/envs/wheel_1/lib/python3.6/site-packages/h2o4gpu/utils/extmath.py", line 26, in <module>
    from .sparsefuncs_fast import csr_row_norms
ImportError: /root/anaconda2/envs/wheel_1/lib/python3.6/site-packages/h2o4gpu/utils/sparsefuncs_fast.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
>>> 
```
BTW, I build h2o4gpu from source/git project and installed it using `make fullinstall`, it' ok. And, I also get a whl file in `XXXXXX/build` directory, I can use normally and install my own building wheel. So,  is it placed incorrectly?  Thanks!
