### ISSUE TITLE
Add standard xgboost tests to list of tests.

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#234]
Only issue is tests are often nose tests and not pytests.  But need to test this since github.com/h2oai/xgboost h2oai branch being used isn't otherwise itself tested, and it's diverged from dmlc/xgboost master branch.

**Comment by pseudotensor** [comment]
https://docs.pytest.org/en/latest/nose.html

https://wiki.jenkins.io/display/JENKINS/Version+Number+Plugin

**Comment by mdymczyk** [comment]
Should we run those tests as part of h2o4gpu or make a new build for XGBoost repo? Think we only want to run them when something in XGBoost changes? And eventually have some h2o4gpu+xgboost specific tests here (i.e. testing the interaction between the two).

**Comment by pseudotensor** [comment]
Well, could jenkins-ify the entire h2oai branch of our xgboost repo, but I'd prefer to keep h2o4gpu as self-contained as possible.  We do have some xgboost specific tests in h2o4gpu, but I prefer that someone can easily test the xgboost side if they want.  It's easy enough and the tests don't take very long.

**Comment by mdymczyk** [comment]
Do you know how long do they take exactly?

**Comment by pseudotensor** [comment]
Doing all the python tests takes 5 minutes, but not all pass (on purpose), so have to loop over each one and check if passes or fails in expected way.

**Comment by mdymczyk** [comment]
5 min should be ok, especially if me and @abal5 will get around to parallelizing the build. Not sure if possible but ideally I'd like:

-3 builds in parallel a) normal build + tests b) nonccl cuda8 build c) nonccl cuda9 build
- if all of the above pass then a publishing task that would publish all artifacts from above

For jobs that build but don't run I think we can utilize linux machines with CUDA installed even if there's no GPU present?

ad. tests - I see, you mean like they throw exceptions on purpose etc. or something else? with exceptions, I think we might be able to write tests to check if an exception was thrown and only fail the test if not (and that would be an actual failure).

**Comment by pseudotensor** [comment]
There are some gpu tests there, so need gpus.  It's possible there should be no errors, but that they don't check all the tests during their dmlc jenkins-like runs.  I'll look into it when I get to this.

**Comment by pseudotensor** [comment]
Better to have h2oai/xgboost h2oai branch as separate jenkins pipeline
