### ISSUE TITLE
Invalid Predictions when using one-hot-encoding

### ISSUE THREAD

**Issue by wamsiv** [h2oai/h2o4gpu#242]
### Environment (for bugs)

- **OS platform, distribution and version (e.g. Linux Ubuntu 16.04)**: Centos
- **Installed from (source or binary)**: binary
- **Version**: 0.0.4
- **Python version (optional)**: 3.5.3
- **CUDA/cuDNN version**: 
- **GPU model (optional)**:
- **CPU model**:
- **RAM available**:

### Description
When `one-hot-encoding` is performed on a data before feeding to to `h2o4gpu.ElasticNetH2O` the predictions are either zero or invalid. (When using separate data for training and prediction)

I have attached the results of `one-hot-encoding` and `scaling` on same dataset with same columns but predictions were Invalid in the former case.

@pseudotensor I did double check if there was/is any problem during data manipulation, but the order of the data seems to be same for both sets (training and prediction). Made sure that order of the columns remain same. Kindly refer the notebooks and let me know if any questions on it.

[Mapd_col.zip](https://github.com/h2oai/h2o4gpu/files/1403296/Mapd_col.zip)

**Comment by wamsiv** [comment]
Copying @sklam for his confirmation on the above issue.

**Comment by mdymczyk** [comment]
@navdeep-G can you have a look at this?

**Comment by pseudotensor** [comment]
No, I asked Wamsi to reduce to simple case.  He has before has issues that ended up his own issues.  We can't degug reasonably until someone gives a simple repro case

**Comment by wamsiv** [comment]
Root cause: `one-hot-encoding` was generating different feature columns for separate training and test sets (due to different number of unique values(rows) for a column). Since, different sets of features were generated, we were getting invalid invalid predictions. Would be useful to use label encoding for these cases.

Attaching a simple reproducible script. 
[h2oglm_test.py.zip](https://github.com/h2oai/h2o4gpu/files/1416492/h2oglm_test.py.zip)

Closing the issue.
