### ISSUE TITLE
Try to remove requirement of gcc>=4.9

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#246]

**Comment by mdymczyk** [comment]
Isn't that a CUDA requirement?

**Comment by mdymczyk** [comment]
GCC 4.9 is required for OMP task dependencies which were introduced in OMP 4.0 which are only supported in GCC 4.9 and newer.

IIRC 4.8 branch is not maintained anymore so unless we get a whole lot of requests to support it I wouldn't go forward with this.

**Comment by pseudotensor** [comment]
Ok, I guess if someone comes along we can point them to this github issue and just assume the requirement we list on the README is sufficient.  I'll close then, thanks!
