### ISSUE TITLE
testperf always failed

### ISSUE THREAD

**Issue by memory-yancy** [h2oai/h2o4gpu#252]
### Prerequisite:

OS: Ubuntu 16.04, RAM available11G , Intel(R) Xeon(R) CPU
CUDA: 8.0 
gcc: 5.4.0-6ubuntu1~16.04.5
h2o4: 0.0.4, download h2o4gpu whl file from anaconda cloud 
     https://anaconda.org/gpuopenanalytics/h2o4gpu
Python: 3.6, use Anaconda3 

### How

I cloned h2o4gpu project, and then I run relevant make subcommand when my env is ready to complete. 
When I run `make testperf`, the `build` subcommand runs ok, but run `dotestperf` subcommand will fail.  Relevant error info: 
```# for pycharm
ln -sf "/root/h2o4gpu/src/interface_py"/build/lib/ch2o4gpu_cpu.so .
ln -sf "/root/h2o4gpu/src/interface_py"/build/lib/ch2o4gpu_gpu.so .
make[1]: Leaving directory '/root/h2o4gpu/src/interface_py'
mkdir -p ./tmp/
H2OGLM_PERFORMANCE=1 pytest -s --verbose --durations=10 -n 1 --fulltrace --full-trace --junit-xml=build/test-reports/h2o4gpu-test.xml tests_open 2> ./tmp/h2o4gpu-test.9174_2017.10.25-15:48:14.log
Makefile:364: recipe for target 'dotestperf' failed
make: *** [dotestperf] Error 2
```
When I check error log, I find pytest run error:
```
root@sd002024:~/h2o4gpu# cat ./tmp/h2o4gpu-test.9174_2017.10.25-15\:48\:14.log 
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n tests_open
  inifile: None
  rootdir: /root/h2o4gpu
```
So, I check again my pytest version and pytest --help output info, not get any valid info about parameter. 
```
root@sd002024:~/h2o4gpu# pip freeze | grep pytest
pytest==3.2.3
```
The solution is:
delete -n parameter in Makefile and try again, but I got another error ... ...

ImportError: cannot import name 'TruncatedSVDH2O

```
__________________________________________________________________________________________________ ERROR collecting tests_open/test_tsvd.py __________________________________________________________________________________________________
ImportError while importing test module '/root/h2o4gpu/tests_open/test_tsvd.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests_open/test_tsvd.py:6: in <module>
    from h2o4gpu.solvers import TruncatedSVDH2O
E   ImportError: cannot import name 'TruncatedSVDH2O'
```
So, based on above error, I check again:

```
(test) root@sd002024 test# python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h2o4gpu
>>> from h2o4gpu.solvers import TruncatedSVDH2O
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TruncatedSVDH2O'
>>> dir(h2o4gpu.solvers)
['ElasticNet', 'ElasticNetH2O', 'KMeans', 'Lasso', 'LinearRegression', 'LogisticRegression', 'Pogs', 'Ridge', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'elastic_net', 'kmeans', 'lasso', 'linear_regression', 'logistic', 'pogs', 'ridge', 'utils']
>>> 
```
So, h2o4gpu don't have TruncatedSVDH2O class, any ideas or bug ?

**Comment by mdymczyk** [comment]
@memory-yancy the version on anaconda cloud is a bit dated - we added TruncatedSVD just recently. You'll have to either remove the current Python package manually and build the whole project yourself (`make fullinstall`) or download one of our bleeding-edge wheels (links in the main readme).

**Comment by mdymczyk** [comment]
@memory-yancy as for `pytest: error: unrecognized arguments: -n tests_open` - this occurs when you don't have `pytest-xdist` installed. We have it in our `requirements-buildonly.txt`, which is not bundled with the wheel.

In general, if you want to run our tests its a good idea to build the project yourself, then you don't have to worry about missing dependencies etc.

**Comment by pseudotensor** [comment]
@mdymczyk It's a good point thought that a user should be able to install a wheel and with the build still test.  But in any case, we already have github issue where all tests will be implanted directly into the code instead of separate, like sklearn, so can test anything from the wheel alone.
