### ISSUE TITLE
Warning: ch2o4gpu_cpu.so failed to load.

### ISSUE THREAD

**Issue by PlayMen** [h2oai/h2o4gpu#257]
Hi,

I run k-means demo from https://github.com/h2oai/h2o4gpu/blob/master/examples/py/demos/H2O4GPU_KMeans_Homesite.ipynb
I have following warning:  h2o4gpu_kmeans_lib shared object (dynamic library) ch2o4gpu_cpu.so failed to load.

OS Rhel 7.2
Installed from https://s3.amazonaws.com/artifacts.h2o.ai/releases/bleeding-edge/ai/h2o/h2o4gpu/0.0.4/h2o4gpu-0.0.4-py36-none-any.whl
Python 3.6
CUDA 8
GPU: 2x Tesla K80
CPU: CPU Model: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
RAM: 504GB

I have model prediction close to expected, but I worry about this warning, could it cause any errors during computations or cause perf degradations?

**Comment by mdymczyk** [comment]
@PlayMen if you're running on GPUs (our default, you can check if they are used by checking `nvidia-smi`) then no. That `*_cpu.so` file is only used in case you choose `n_gpus=0` in our algorithms.

That being said I'd like to investigate a bit more, since we only run tests on Ubuntu. What is your gclib version (you can find out by running `ldd --version`) and gcc version (`gcc --version`)?

Were there any other warnings during instalation/runtime?

**Comment by PlayMen** [comment]
Hi,

I ran on GPU, with nvidia-smi I could see both GPU utilized. 
ldd --version
ldd (GNU libc) 2.17

gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

I don't remember other warnings, except that I had to call conda install libgcc to work.

**Comment by PlayMen** [comment]
P.S. Thanks for fast reply!

**Comment by mdymczyk** [comment]
@PlayMen `gclib 2.17` might be a problem - we're building the wheel on a system with `2.23`. I'm a bit surprised this worked for you at all.

I know RHEL might not yet have an official 2.23 glibc binary, we're trying to figure out a way to build a more robust whl file that would also work on other distros (CentOS and RHEL at least).

**Comment by PlayMen** [comment]
Ok, thanks for your help again!

**Comment by pseudotensor** [comment]
According to auditwheel, one just has to compile against an old glibc.  This is mentioned in the other github issue about the fpectl issue.

**Comment by mdymczyk** [comment]
@pseudotensor yes, but we need to setup a build system with a lower glibc. Whether this will be trivial or not, I don't know. For Ubuntu the NVidia CUDA requirements say we should use 2.23, so I'm not sure if we can just downgrade glibc in our docker and it will work. Otherwise we'd need to either try and downgrade the Ubuntu version in our docker to a version that can handle glibc 2.17 (not sure if 14.04 can or does it require 2.19?) or we'd need to rewrite our docker for CentOS/RHEL.

**Comment by pseudotensor** [comment]
Ya, we can't go below cuda8 requirement for glibc.

**Comment by ben-campbell** [comment]
I see this error when attempting to run H2O4GPU on a fresh AWS node, Ubuntu 16.0.4, g3.4x (1 NVIDIA M60).

Here are my steps:

### NVIDIA CUDA:

Dependencies:

```
sudo apt-get update -y
sudo apt-get install -y gcc
sudo apt-get isntall -y make
```

NVIDIA CUDA 9.1 — check [here](https://developer.nvidia.com/cuda-downloads) for up-to-date links:

```
wget https://developer.nvidia.com/compute/cuda/9.1/Prod/local_installers/cuda_9.1.85_387.26_linux
mv cuda_9.1.85_387.26_linux cuda_9.1.85_387.26_linux.run
sudo sh cuda_9.1.85_387.26_linux.run
```

Verify drivers installed:

```
nvidia-smi
```

### Python

To install Python3.6 via apt-get on Ubuntu 16.0.4:
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.6
sudo rm /usr/bin/python3
sudo ln -s /usr/bin/python3.6 /usr/bin/python3
sudo apt-get install python3.6-dev
sudo apt-get install python3-pip
```
### H2O4GPU

Dependency:
```
sudo apt-get install libopenblas-base
```

Get and install python package:

```
wget https://s3.amazonaws.com/h2o-release/h2o4gpu/releases/bleeding-edge/ai/h2o/h2o4gpu/0.2-nccl-cuda9/h2o4gpu-0.2.0-cp36-cp36m-linux_x86_64.whl
pip install h2o4gpu-0.1.0-py36-none-any.whl
```

Try H2O4GPU:

```
python3
>>> import h2o4gpu
>>> import numpy as np
>>> X = np.array([[1.,1.], [1.,4.], [1.,0.]])
>>> model = h2o4gpu.KMeans(n_clusters=2,random_state=1234).fit(X)

Warning: h2o4gpu_kmeans_lib shared object (dynamic library) /home/ubuntu/.local/lib/python3.6/site-packages/h2o4gpu/libs/../../ch2o4gpu_gpu.so failed to load.

>>> model.cluster_centers_
array([[1. , 0.5],
       [1. , 4. ]])
```

**Comment by mdymczyk** [comment]
@ben-campbell we don't support CUDA 9.1, only 9.0. This might be one reason. Also I'm assuming this `pip install h2o4gpu-0.1.0-py36-none-any.whl` is a typo and you are actually installing the `0.2.0` you downloaded with wget?

**Comment by ben-campbell** [comment]
@mdymczyk yes, it was simply CUDA 9.1 vs. 9.0... d'oh.  

The above is now correct (just tested on a fresh AWS Ubuntu 16.0.4 g3.4x instance).  It might be a good idea to add this to the docs, to ease the install on AWS for others.

**Comment by arunsrinivasan** [comment]
I'm trying to get the test code to run on an Amazon P3 instance. I get the `ch2o4gpu_gpu.so failed to load` issue.. I've been at this for a while now, and would really appreciate any pointers...

Here are the details:

### Amazon P3 instance with Tesla V100

```
[~]$ uname -r
4.9.81-35.56.amzn1.x86_64
```
### CUDA version and ./deviceQuery output (which PASSes)

```
[site-packages]$ /data/cuda9/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

[deviceQuery]$ ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "Tesla V100-SXM2-16GB"
  CUDA Driver Version / Runtime Version          9.0 / 9.0
  CUDA Capability Major/Minor version number:    7.0
  Total amount of global memory:                 16152 MBytes (16936927232 bytes)
  (80) Multiprocessors, ( 64) CUDA Cores/MP:     5120 CUDA Cores
  GPU Max Clock rate:                            1530 MHz (1.53 GHz)
  Memory Clock rate:                             877 Mhz
  Memory Bus Width:                              4096-bit
  L2 Cache Size:                                 6291456 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Enabled
  Device supports Unified Addressing (UVA):      Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 0 / 30
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.0, CUDA Runtime Version = 9.0, NumDevs = 1
Result = PASS
```

### NVIDIA graphics driver

```
[deviceQuery]$ nvidia-smi
Fri Mar  2 19:06:03 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   40C    P0    36W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

### glibc and gcc version

```
[~]$ ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

[~]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### LDD output (as per FAQ)

```
[site-packages]$ ldd ch2o4gpu_gpu.so
        linux-vdso.so.1 =>  (0x00007ffc832ad000)
        libcudart.so.9.0 => /usr/local/cuda/lib64/libcudart.so.9.0 (0x00007f3eafbac000)
        libcublas.so.9.0 => /usr/local/cuda/lib64/libcublas.so.9.0 (0x00007f3eac776000)
        libcusolver.so.9.0 => /usr/local/cuda/lib64/libcusolver.so.9.0 (0x00007f3ea7b7b000)
        libcusparse.so.9.0 => /usr/local/cuda/lib64/libcusparse.so.9.0 (0x00007f3ea4415000)
        libblas.so.3 => /usr/lib64/libblas.so.3 (0x00007f3ea41be000)
        libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00007f3ea3f91000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f3ea3c0c000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f3ea390a000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f3ea36f4000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f3ea3330000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f3ea312c000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3ea2f10000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f3ea2d08000)
        libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x00007f3ea29e2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3eb28da000)
        libquadmath.so.0 => /usr/lib64/libquadmath.so.0 (0x00007f3ea27a3000)
```

### Test run (from README)

```
[~]$ python3
Python 3.6.2 (default, Feb 19 2018, 21:55:54)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h2o4gpu
>>> import numpy as np
>>> X = np.array([[1.,1.], [1.,4.], [1.,0.]])
>>> model = h2o4gpu.KMeans(n_clusters=2,random_state=1234).fit(X)

# Warning: h2o4gpu_kmeans_lib shared object (dynamic library) /usr/local/lib/python3.6/site-packages/h2o4gpu/libs/../../ch2o4gpu_gpu.so failed to load.

# Warning: h2o4gpu_kmeans_lib shared object (dynamic library) /usr/local/lib/python3.6/site-packages/h2o4gpu/libs/../../ch2o4gpu_cpu.so failed to load.
>>> model.cluster_centers_
# array([[1. , 0.5],
#       [1. , 4. ]])
```

Also note that the output from ben-campbell matches the one shown above, but it's different from the one under README.

**Comment by mdymczyk** [comment]
@arunsrinivasan this is because the system you're trying to run uses glibc 2.17. We are building with Ubuntu 16.04 which (iirc) uses glibc 2.23 (or some other 2.2x). If your system has binaries for glibc 2.23+ you'd need to upgrade. Some distros (like Centos or RHEL) don't. In such a case you'd have to build the project yourself (clone the repo and run `make fullinstall`). We'll have more generic binaries sometime in the future but not very soon I think as it requires us to redo our whole build process under Centos/RHEL.

**Comment by arunsrinivasan** [comment]
@mdymczyk thanks for the quick reply. Will try that and write back.

**Comment by nikolayvoronchikhin** [comment]
Hello @mdymczyk , do you have an ETA when the h2o4gpu-0.2.0-cp36-cp36m-linux_x86_64.whl will be available for RHEL 7.x OS?

**Comment by mdymczyk** [comment]
@nikolayvoronchikhin the bleeding edge should already work, please use that. It's pretty stable, we just didn't have time to make a proper release cut.

**Comment by nikolayvoronchikhin** [comment]
Hello @mdymczyk , we tried to build it using **make fullinstall** and got stuck at this error:

Installing collected packages: numpy, scipy, xgboost
Successfully installed numpy-1.15.1 scipy-1.1.0 xgboost-0.80
Target directory ~/h2o4gpu/xgboost/python-package/xgboost already exists. Specify --upgrade to force replacement.
----- Building LightGBM target  -----
See https://github.com/Microsoft/LightGBM/wiki/Installation-Guide#with-gpu-support for details
sudo apt-get install libboost-dev libboost-system-dev libboost-filesystem-dev cmake
if [ `arch` != "ppc64le" ]; then \
cd LightGBM && (rm -rf build || true) && mkdir -p build && \
sed -i 's/#define BOOST_COMPUTE_USE_OFFLINE_CACHE//g' src/treelearner/gpu_tree_learner.h && \
cd build && \
cmake .. -DUSE_GPU=1 -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include/ -DBOOST_ROOT=/opt/boost -DBoost_USE_STATIC_LIBS=ON -DBoost_NO_SYSTEM_PATHS=ON && \
make OPENCL_HEADERS=/usr/local/cuda/targets/x86_64-linux/include LIBOPENCL=/usr/local/cuda/targets/x86_64-linux/lib -j && cd .. && \
cd python-package &&  sed -i 's/self\.gpu \= 0/self.gpu = 1/g' setup.py && cd .. && \
cd python-package &&  sed -i 's/self\.precompile \= 0/self.precompile = 1/g' setup.py && cd .. && \
cd python-package && rm -rf dist && (python setup.py sdist bdist_wheel || true) && cd .. && \
cd python-package && cd compile && (true || ln -fs ../../include .) && cd ../../ && \
cd python-package && rm -rf dist && (python setup.py sdist bdist_wheel || true) && cd .. && \
cd python-package && cd compile && (true || ln -fs ../../src .) && cd ../../ && \
cd python-package && rm -rf dist && (python setup.py sdist bdist_wheel || true) && cd .. && \
cd python-package && cd compile && (true || ln -fs ../../compute .) && cd ../../ && \
cd python-package && rm -rf dist && python setup.py sdist bdist_wheel && \
python -m pip install arff tqdm keras runipy h5py ; \
fi
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")  
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /usr/local/cuda/lib64/libOpenCL.so (found version "1.2") 
-- OpenCL include directory:/usr/local/cuda/include
CMake Warning at /usr/share/cmake3/Modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindBoost.cmake:959 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake3/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:86 (find_package)

CMake Warning at /usr/share/cmake3/Modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindBoost.cmake:959 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake3/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:86 (find_package)

CMake Error at /usr/share/cmake3/Modules/FindBoost.cmake:2044 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:86 (find_package)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory ~/h2o4gpu/LightGBM

-- Configuring incomplete, errors occurred!
See also "~/h2o4gpu/LightGBM/build/CMakeFiles/CMakeOutput.log".
See also "~/h2o4gpu/LightGBM/build/CMakeFiles/CMakeError.log".
make: *** [lightgbm] Error 1
[~ h2o4gpu]$
