### ISSUE TITLE
Cleanup requirements.txt and setup.py requirements

### ISSUE THREAD

**Issue by mmalohlava** [h2oai/h2o4gpu#267]
The problem right now, that `setup.py` is reading `requirements.txt` which is bloated by unnecessary packages (jupyter, seaborn) - this pollutes installation of scoring package in h2oai project (CC: @lo5 )

Background:
  - setup.py should clearly list minimal installation requirements. 
  - requirements.txt should list all requirements which are needed for "comfortable" run of the project.

For more details see PyPa template for setup.py: https://raw.githubusercontent.com/pypa/sampleproject/master/setup.py

**Comment by pseudotensor** [comment]
We only use requirements_runtime.txt for h2o4gpu.  These are all the packages needed to run h2o4gpu as well as the demos.  I think what you are saying is to remove the requirements for demos and maybe have a separate requirements_demos.txt.

**Comment by pseudotensor** [comment]
I don't see that the template helps at all.

**Comment by pseudotensor** [comment]
Probably the best solution is to create a stripped-down wheel for h2oai, but keep the wheel on the README and for the container as normal for h2o4gpu.  This is easy as wheel generation is very quick, and it's just another artifact to push to s3 that h2oai would use instead.

**Comment by mmalohlava** [comment]
The template just explains difference between install_requires and requirements.txt.
But yes, it is painful part of python. 

I like your idea having multiple requirements file - e.g.,  minimal requirement file which is used in setup.py? if you would like to have a single place definition.
