### ISSUE TITLE
More Jenkins todo list (please contribute to list and start to prioritize)

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#277]
~1) versioning~

~2) Add containers wheel cuda8/cuda9 links on README.  Update links to cuda8/cuda9 etc. wheels.~

~Do this automatically instead of hard-coding.~

3) have sklearn as import instead of complicated submodule (so no longer compile sklearn).  Wheel should then be more general, although still x86 due to C backend.

~4) name artifacts correctly and well~

https://github.com/h2oai/h2o4gpu/pull/291

~5a) Loop over builds as functions instead of copy/pasted stuff.~

~https://stackoverflow.com/questions/42158539/how-to-define-and-use-function-inside-jenkins-pipeline-config~
~https://github.com/h2oai/xgboost/blob/4d8433f145b4f3da0c60c69a9b0c9be8e1e52dd0/Jenkinsfile~

~5b) Parallel build for all cuda~ and python versions.  ~Even parallel on same machine (compile uses not too many cores most of the time)~

~https://stackoverflow.com/questions/43913698/jenkinsfile-parallel-directive~
~https://jenkins.io/doc/pipeline/examples/#jobs-in-parallel~

~NOTE: Can just have multiple Jenkinsfile(s) and pass into them the nccl/nonccl cuda8/cuda9 tags to control which is done from a Jenkins config in the browser.  Then the builds will be in full parallel mode more easily.  I'm not sure how this will show up in github/jenkins.~

~6) Have make smoke for build to do basic tests of other builds and containers (only do full make test once)~

~7) Have h2oai/xgboost repo in h2oai branch build wheel as separate jenkins pipeline and pushed to s3.  (This way don't have to build xgb everytime h2o4gpu built.)~

~https://github.com/h2oai/h2o4gpu/pull/291~
~https://github.com/h2oai/xgboost/commit/db585d1c04763d7f08eb1fec59e03c72faeefd36~

8) make testperf as benchmark if triggered by (say) #benchmark in commit or if any filles in src are changed. (like DAI for h2oaicore files)

~9) Currently, a PR skips pushing to s3, but then runtime build pulls the h2o4gpu wheel from s3.  I notice some PR version gets pushed to s3, shoudl use that for runtime during PR.  But then when are those PR s3 pushes deleted?  Do they just accumulate?  Note that master will have the correct build process, but the PR won't be creating the correct runtime docker file (in case that is used for the PR itself, but currently it is not -- which makes this not a super high priority).~

~10) If upload docker runtime (big!) during PR, need to delete old PRs frequently to avoid bloat on S3.~

**Comment by mdymczyk** [comment]
@pseudotensor @navdeep-G  think we can decide on the versioning schema tomorrow during the weekly meeting? If we decide on 1) how we want the version to work 2) how we want to release the project I can implement it after the meeting.

**Comment by sh1ng** [comment]
Obsolete
