### ISSUE TITLE
`make testbigperf` fails at `aws s3 sync` command

### ISSUE THREAD

**Issue by michael-balint** [h2oai/h2o4gpu#306]
Running `make testbigperf` fails when reaching `sync_otherdata`...

```
---- Synchronizing data dir in test/ ----
mkdir -p ./
aws s3 sync --recursive "s3://h2o-datasets/h2o4gpu/data" "./"

Unknown options: --recursive
Makefile:96: recipe for target 'sync_otherdata' failed
make: *** [sync_otherdata] Error 255
```

Substituting `--no-sign-request` instead of `--recursive` yields an `Access Denied` error...

```
$ aws s3 sync --no-sign-request "s3://h2o-datasets/h2o4gpu/data" "./"
fatal error: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
```

AWS CLI version...

```
$ aws --version
aws-cli/1.12.0 Python/3.6.1 Linux/4.4.0-83-generic botocore/1.8.0
```

**Comment by pseudotensor** [comment]
The make testbigperf requires one to run make sync_otherdata or make sync_data but that goes to a closed s3 bucket.  I can share the data with you if you provide a means to upload it.

**Comment by pseudotensor** [comment]
But I fixed the --recursive and (for me with access to that bucket) the make testbigperf works. b2efce00922af163fbc82032dbb2c433f5718e0b
