### ISSUE TITLE
Fix versioned s3 uploads so runtime docker has no snapshots, only bleeding edge and stable.  Otherwise too storage taken up.

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#315]
https://s3.console.aws.amazon.com/s3/buckets/h2o-release/h2o4gpu/snapshots/bleeding-edge/ai/h2o/h2o4gpu/0.1-nonccl-cuda8/?region=us-east-1&tab=overview

**Comment by pseudotensor** [comment]
Seems for h2o-release/h2o4gpu, don't need to have the /ai/h2o/h2o4gpu part.  Redundant for snapshots in this bucket.

**Comment by sh1ng** [comment]
It's already fixed https://github.com/h2oai/h2o4gpu/blob/master/ci/Jenkinsfile.utils#L177-L180
