### ISSUE TITLE
XGBoost wrappers calling incorrect methods

### ISSUE THREAD

**Issue by mdymczyk** [h2oai/h2o4gpu#331]
https://github.com/h2oai/h2o4gpu/blob/master/src/interface_py/h2o4gpu/solvers/xgboost.py#L720

The `GradientBoostingRegressor` is calling `XGBClassifier` instead of `XGBRegressor`.

Also the `GradientBoostingClassifier` https://github.com/h2oai/h2o4gpu/blob/master/src/interface_py/h2o4gpu/solvers/xgboost.py#L427 is using `num_parallel_tree=100` which is too large, we should go (probably) with 1.

Also unit tests need to add `h2o4gpu` backend assertions, now assertions are called only for `sklearn` backend.

**Comment by pseudotensor** [comment]
Yes, noticed those a few days ago and didn't have time to fix (was planning to eventually).  Thanks for posting the issue.
