### ISSUE TITLE
Kmeans: KMeans|| too slow compared to init='random'

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#333]
On default homesite notebook, takes 1:10 on single 1080ti with kmeans||, but only 10s with init_random.  CPU/GPU usage shows hits GPU at first, but spends most of the time on the CPU, and does a bit more on the GPU at the end.

**Comment by mdymczyk** [comment]
3 potential speedups, at the last stage of kmeans||:

1) do the martix multiplication on GPU not CPU
2) try not to erase data from middle of vectors as it might be expensive
3) dont create vectors each iteration
