### ISSUE TITLE
KMeans: Multi-GPU performance saturated even with init='random'

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#334]
10-15s with 1 or 2 GPUs on 1080ti for homesite kmeans notebook.  As if (compared to previously) improvements allowed for across the board for all GPU counts, but saturated in performance for a different reason that was possibly related to why 4 and 8 GPUs had similar performance before.

**Comment by mdymczyk** [comment]
One issue I noticed is even if we set `random_state=1` in both cases (1 and 2 gpu), the total number of iteration differs. 2 GPU version is running for over 200iter, while 1 GPU version finishes around 150. Both cases are reproducible (i.e. 1GPU always runs for ~150, 2GPU always ~200) but they should be both similar. The only reason why this would happen I can come up with on the spot is because in 1GPU case we do scaling on the GPU while in the 2GPU version on the CPU.

**Comment by pseudotensor** [comment]
On volta I get very poor performance with the kmeans image notebook.

GPU#   Time for fit
1            44s
2            29s
4            24s
8            30s # after warmup
8            45s  # first time run on gpus

The first time ran, it seems to be sequentially allocating on the GPU, as if you have some cuda operation (e.g. sync or info getter) that is sequential and getting the cuda context setup sequentially).  Need to avoid that.

For post-warmup, see low GPU usage for 8 GPUs:

![image](https://user-images.githubusercontent.com/2249614/33901172-cc0d7d6a-df25-11e7-8c10-1b64fd33a252.png)

**Comment by pseudotensor** [comment]
Even larger works, although slow.

![image](https://user-images.githubusercontent.com/2249614/38060274-e8b1d340-329e-11e8-8b29-b0d5cb5c5a5f.png)

spends most of the time on the CPU doing single-threaded work.  Pokes on the GPU (1 at a time) sometimes.

Only after a while does it do use all GPUs in parallel:

![image](https://user-images.githubusercontent.com/2249614/38060353-2713b0ea-329f-11e8-8596-09ded3e5b48b.png)

Then it goes back to single-threaded stuff on CPU with no GPU usage.

![image](https://user-images.githubusercontent.com/2249614/38060358-349b240a-329f-11e8-885d-e28f8291eb73.png)

**Comment by pseudotensor** [comment]
```
import h2o4gpu
import numpy as np
>>> X = np.random.rand(80636906,34)                               
>>> model = h2o4gpu.KMeans(n_clusters=5,random_state=1234).fit(X) 
Segmentation fault (core dumped) 
```

**Comment by pseudotensor** [comment]
```
ython 3.6.4 (default, Mar 23 2018, 19:10:33) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h2o4gpu
>>> import numpy as np
>>> X = np.random.rand(80636906*3,50)
model = h2o4gpu.KMeans(n_clusters=5,random_state=1234).fit(X)
>>> model = h2o4gpu.KMeans(n_clusters=5,random_state=1234).fit(X)
>>> y = np.random.rand(80636906, 15)
>>> model = h2o4gpu.KMeans(n_clusters=5,random_state=1234).fit(y)
>>> %model = h2o4gpu.KMeans(n_clusters=5,random_state=1234).fit(y)
  File "<stdin>", line 1
    %model = h2o4gpu.KMeans(n_clusters=5,random_state=1234).fit(y)
    ^
SyntaxError: invalid syntax
>>> import time
>>> starttime=time.time() ; model = h2o4gpu.KMeans(n_clusters=5,random_state=1234).fit(y) ; diff=time.time()-starttime
>>> starttime=time.time() ; model = h2o4gpu.KMeans(n_clusters=5,random_state=1234, n_gpus=4).fit(y) ; diff4=time.time()-starttime
>>> diff
16.521016120910645
>>> diff4
18.117528438568115
>>> starttime=time.time() ; model = h2o4gpu.KMeans(n_clusters=5,random_state=1234, n_gpus=2).fit(y) ; diff2=time.time()-starttime
>>> diff2
26.564540147781372
>>> 
```
Couldn't do 1 GPU, wouldn't fit. Could redo, but too late.

So at least not slower with 8 GPUs, but not much faster.  Mostly limited by transfer and kmeans|| I think, but probably other improvements can be made.

Also can do big problem not possible on less GPUs:

![image](https://user-images.githubusercontent.com/2249614/38078915-9740eb32-32f2-11e8-9d3c-9020664d5dba.png)
