### ISSUE TITLE
/usr/lib/libblas.so.3: undefined symbol: gotoblas

### ISSUE THREAD

**Issue by gitclem** [h2oai/h2o4gpu#345]
I'm having trouble with running some bits of h2o4gpu.   I get the error:

```
print(get_compute_capability(0))
/usr/lib/libblas.so.3: undefined symbol: gotoblas

Warning: h2o4gpu_glm_lib shared object (dynamic library) /usr/local/anaconda3/lib/python3.6/site-packages/h2o4gpu/libs/../../ch2o4gpu_gpu.so failed to load. 
Exception
/usr/lib/libblas.so.3: undefined symbol: gotoblas

Warning: h2o4gpu_glm_lib shared object (dynamic library) /usr/local/anaconda3/lib/python3.6/site-packages/h2o4gpu/libs/../../ch2o4gpu_cpu.so failed to load. 
(0, 0, 0)
In [13]:

```

I believe I have things installed correctly:

```
$ sudo apt-get install libopenblas-dev pbzip2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopenblas-dev is already the newest version (0.2.18-1ubuntu1).
pbzip2 is already the newest version (1.1.9-1).
0 upgraded, 0 newly installed, 0 to remove and 198 not upgraded.

```

I'm using Ubuntu 16.04

**Comment by pseudotensor** [comment]
It's probably an anaconda issue.  We don't support anaconda yet.  You can try the command on the README for installing the anaconda version, but we don't support it.

**Comment by mdymczyk** [comment]
@gitclem like @pseudotensor this will be a problem with Anaconda env. You are installing `libopenblas-dev` but anaconda dev is using `libblas` (not OPENbls) which iirc are two different things. I'd try to install https://anaconda.org/anaconda/libopenblas instead and get rid of libblas.
