### ISSUE TITLE
R test failure (test_model.R)

### ISSUE THREAD

**Issue by navdeep-G** [h2oai/h2o4gpu#404]
Loading h2o4gpu
Loading required package: testthat
Testing h2o4gpu
✔ | OK F W S | Context
✖ |  0 1     | Test h2o4gpu_model methods [0.9 s]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
???: failure: Generic methods for model work correctly for different types of inputs
`force(expr)` threw an error.
Message: cannot coerce class "c("numpy.ndarray", "python.builtin.object")" to a data.frame
Class:   simpleError/error/condition

**Comment by navdeep-G** [comment]
Only fails in test infrastructure. Passes locally. cc @terrytangyuan

**Comment by terrytangyuan** [comment]
For the record, here's the error message from @navdeep-G:
```
1: as.data.frame(x) at /home/navdeep/h2o4gpu/src/interface_r/tests/testthat/test_model.R:9
2: as.data.frame.default(x)
3: stop(gettextf("cannot coerce class \"%s\" to a data.frame", deparse(class(x))), domain = NA)

Message: cannot coerce class "c("numpy.ndarray", "python.builtin.object")" to a data.frame
Class: simpleError/error/condition
```

Could you give little more details on how you executed the tests? You mentioned R CMD test but did you run it through console or through RStudio IDE?

**Comment by terrytangyuan** [comment]
What is your version of devtools and testthat?

**Comment by navdeep-G** [comment]
Ran it through RStudio IDE.

Version of devtools and testthat:
```
> packageVersion("testthat")
[1] ‘2.0.0’
> packageVersion("devtools")
[1] ‘1.13.4’
```
