### ISSUE TITLE
fullinstall broken.  Needs R with specific version, etc.

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#410]
I don't have it, but it should be installed as part of dependency.
```
 Test R package
/usr/bin/R-3.1.0 -e 'devtools::test("src/interface_r")'
/bin/bash: /usr/bin/R-3.1.0: No such file or directory
Makefile:468: recipe for target 'dotest' failed
make: *** [dotest] Error 127
jon@pseudotensor:~/h2o4gpu$ 
```

**Comment by pseudotensor** [comment]
Nothing in https://github.com/h2oai/h2o4gpu/blob/master/DEVEL.md about it either.

**Comment by terrytangyuan** [comment]
Ok, will submit a fix for that. It should be version agnostic.

**Comment by terrytangyuan** [comment]
@pseudotensor Could you give this a try? https://github.com/h2oai/h2o4gpu/pull/413
