### ISSUE TITLE
Methods for model persistence/checkpointing

### ISSUE THREAD

**Issue by terrytangyuan** [h2oai/h2o4gpu#443]
Is this already possible in Python API in a similar fashion to sklearn (e.g. http://scikit-learn.org/stable/modules/model_persistence.html)? What about the H2O ones? @navdeep-G 

We need these methods for R API as well, e.g. invoke the correct methods for models using different implementations.

**Comment by navdeep-G** [comment]
@terrytangyuan I have not looked at this in particular, but I think we should have it. Let me see if it can be done or not.

**Comment by mdymczyk** [comment]
We don't have persistence yet.

Is this something we need right now for R? We can put this in the backlog but we'll have to start focusing on pre-GTC preparations first (getting current algorithms into Flow, preparing a CUDA bootcamp, maybe a 0.1v R API).

**Comment by navdeep-G** [comment]
I think pre-GTC is those points you mentioned. @mdymczyk @ledell @terrytangyuan

**Comment by terrytangyuan** [comment]
Sure, this isn’t R specific. It needs to be done in Python. Isn’t this a must for every users? Imagine you trained a model using GPUs for a couple days but there is no way to save and load it later? Usually for large models the training process needs to be checkpointed on a regular basis in case of failures.

**Comment by terrytangyuan** [comment]
Oh for sure you guys decide priorities for this. I wasn’t aware of GTC - probably you discussed during standup this week.

**Comment by BatuhanKavlak** [comment]
Guys, when, do you think, will this feature available? We can't use it for the thesis since the result is not reproducible.
