### ISSUE TITLE
Possible bug in explained variance/ explained variance ratio

### ISSUE THREAD

**Issue by navdeep-G** [h2oai/h2o4gpu#450]
The differences I am seeing with explained variance and explained variance ratio between CUDA and Python. Done on a 5000 by 50 matrix with k = 2:
Calculation in Python
```
h2o4gpu tsvd Explained Variance
[0.08407421 0.09914753]
Sklearn Explained Variance
[0.08407422 0.09914825]

```
Calculation in CUDA:
```
h2o4gpu tsvd Explained Variance
[0.08407421 0.08716473]
Sklearn Explained Variance
[0.08407422 0.09914825]
```

**Comment by navdeep-G** [comment]
@RAMitchell Any ideas?

**Comment by mdymczyk** [comment]
Is this still the case or did your latest changes fix it? @navdeep-G

**Comment by navdeep-G** [comment]
@mdymczyk I need to double check that to see how it behaves in CUDA
