### ISSUE TITLE
Use  $(PYTHON) -m pip not pip

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#453]
mmalohlava 17 minutes ago  Owner
Reacting to reported feedback from OOS: why pip is hard coded here? the same for python.

It is easier to depend on PYTHON variable which can be redefined by a caller and instead of pip it is possible to use $(PYTHON) -m pip . Quite flexible, helped in DTBL a lot.

      @pseudotensor
pseudotensor 35 seconds ago  Member
Ya, may be good to change. I'm used to using pyenv within which pip is always pointing to correct location.

**Comment by mdymczyk** [comment]
Closing in favor of #564

**Comment by sh1ng** [comment]
I believe we use it almost everywhere. I think we no need a separate issue for such a tiny enhancement.
