### ISSUE TITLE
Split PCA into float and double precision

### ISSUE THREAD

**Issue by navdeep-G** [h2oai/h2o4gpu#463]

**Comment by mdymczyk** [comment]
Like with verbose for PCA, think we can get this done this week or should we move to 0.2.1 milestone?

**Comment by navdeep-G** [comment]
@mdymczyk I don't think its a show stopper. If I can get to it I will add it. Would be nice to have.

**Comment by mdymczyk** [comment]
Yup, definitely one of the issues we can move to 0.2.1 if necessary.
