### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by bnu-unipus** [h2oai/h2o4gpu#484]
when i  try import h2o4gpu after import pygdf.
an import error is arised:

**ImportError: /home/u/anaconda3/lib/python3.6/site-packages/pyarrow/libarrow_python.so.0: undefined symbol: _ZTIN5arrow2io8WritableE**

**Comment by mdymczyk** [comment]
@bnu-unipus this looks like anaconda issue (and a quick google seems to confirm this). Also, even though we have one old build for anaconda, we do not support and test it ourselves.
