### ISSUE TITLE
Standard and Truncated SVD

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#49]
Standard SVD on GPU is in place without API, but holding until can see how to do truncated SVD.  Also, seems sklearn truncated SVD uses lots of memory despite being truncated -- can one optimize more for memory vs. time?

**Comment by mdymczyk** [comment]
Things that require consideration:

- unit tests
- benchmarks against SKLearn: focus on data sizes/parameters used in DriverlessAI but also add general case tests
- has to work both on CPU and GPU, until we have a CPU kernel we should fallback to SKLearn

@navdeep-G

**Comment by navdeep-G** [comment]
@mdymczyk All of those points sound good to me.
