### ISSUE TITLE
Predict type = "prob" not working for GBM and GLM in R

### ISSUE THREAD

**Issue by ledell** [h2oai/h2o4gpu#496]
The `predict(model, test, type = "prob")` functionality is not working for GBMs and GLMs at the moment (two separate errors).

Example:
```
# Load a sample dataset for binary classification
# Source: https://archive.ics.uci.edu/ml/datasets/HIGGS
train <- read.csv("https://s3.amazonaws.com/erin-data/higgs/higgs_train_10k.csv")
test <- read.csv("https://s3.amazonaws.com/erin-data/higgs/higgs_test_5k.csv")

# Create train & test sets (column 1 is the response)
x_train <- train[, -1]
y_train <- train[, 1]
x_test <- test[, -1]
y_test <- test[, 1]

# Train three different binary classification models
model_gbc <- h2o4gpu.gradient_boosting_classifier() %>% fit(x_train, y_train)
model_rfc <- h2o4gpu.random_forest_classifier() %>% fit(x_train, y_train)
model_enc <- h2o4gpu.elastic_net_classifier() %>% fit(x_train, y_train) 

# Generate predictions (type "prob" gives predicted values instead of predicted label)
pred_gbc <- model_gbc %>% predict(x_test, type = "prob")  #broken
pred_rfc <- model_rfc %>% predict(x_test, type = "prob")  
pred_enc <- model_enc %>% predict(x_test, type = "prob")  #broken
```

GBM:
```
> pred_gbc <- model_gbc %>% predict(x_test, type = "prob")
Error in `colnames<-`(`*tmp*`, value = c(0, 1)) : 
  attempt to set 'colnames' on an object with less than two dimensions
```

GLM:
```
> pred_enc <- model_enc %>% predict(x_test, type = "prob")
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'ElasticNet' object has no attribute 'predict_proba'
```

**Comment by mdymczyk** [comment]
@ledell do you think this is Python or R related? `predict_proba` in Python is a method, so should be always present in `ElasticNet` (the previous errors I fixed yesterday were on object properties, which were not set in `__init__` bu instead something like `self.property = value` was done in `fit()`....).

**Comment by terrytangyuan** [comment]
I think I know what the problem is. I will submit a PR so you can test again.

**Comment by terrytangyuan** [comment]
Wait, nvm, is this only happening to those two estimators?

**Comment by ledell** [comment]
@terrytangyuan Can you also make change to `type = c("raw", "prob")` and `type <- match.arg(type)` while you're in the predict code?

**Comment by ledell** [comment]
I think the Elastic Net one is Python related and the GBM bug is probably R code.

**Comment by terrytangyuan** [comment]
I am not sure if this fixes it but could you try the change in this PR? https://github.com/h2oai/h2o4gpu/pull/498

**Comment by terrytangyuan** [comment]
Think I located the problems:

Problem with GLM (on R) is that only `ElasticNetH2O` has `predict_proba`. `ElasticNet` does not have it. 

Problem with GBM (on Python) is this piece of code: https://github.com/h2oai/h2o4gpu/blob/master/src/interface_r/R/model.R#L98

@navdeep-G Could you go from here?

**Comment by navdeep-G** [comment]
@terrytangyuan Yep, I mentioned that last night. Sorry for the wild goose chase.
