### ISSUE TITLE
Improve versioning for bleeding edge releases

### ISSUE THREAD

**Issue by mdymczyk** [h2oai/h2o4gpu#516]
We'd need a way to mark builds/versionins as bleeding edge.

Ideas:

1) ~~append 9999 at the end for BE~~

2) even/odd numbering

Can't use git_hash because of R.

EDIT: added 9999 to the version, not closing as we still need to figure out a way to easily get the build number and/or build date.

**Comment by navdeep-G** [comment]
For R we can do the following:
Start with 0.2.0.9000 upon first arrival for CRAN and then increment from there, e.g. 0.2.0.9001 for a new commit, etc. and then if it’s stable enough we do 0.2.0.9999 and then release 0.2.1

For Python maybe do the same or go the git hash route? I guess consistency is preferred at this point...

**Comment by navdeep-G** [comment]
Some points from @ledell:
```
1. same version in R and python
2. must be a number (bc of R)
3. whl file name can have a hash if we want
4. must be able to tell which version (commit) is being used
```

**Comment by mdymczyk** [comment]
Still to do: a way to get build date in R and Python

**Comment by sh1ng** [comment]
We can just increase version number after release(like https://github.com/microsoft/LightGBM/commits/master/VERSION.txt).
