### ISSUE TITLE
R API Funding: R Consortium Call for Proposals

### ISSUE THREAD

**Issue by jtelleria** [h2oai/h2o4gpu#529]
Dear H2O.ai Developers,

At this moment, the R Consortium is doing a call for those R Projects which will have a broad impact in the R Community:

I consider that h2o4gpu can be one of such projects, so I propose that we complete the paperwork for supporting economically the h2o4gpu R Package:

https://www.r-consortium.org/projects/call-for-proposals

We have till 1st May to Complete such project proposal.

Who is into it? :)

Juan

**Comment by jtelleria** [comment]
If necessary, I can complete such request forms by myself, as I think it will help to push forward this project.

**Comment by terrytangyuan** [comment]
@jtelleria This package is based on top of Python through reticulate so I doubt that there will be too much work on the R side (most of the core pieces are already there).

**Comment by ledell** [comment]
@jtelleria Thanks for the idea, but as @terrytangyuan mentioned, most of the R code is auto-generated so all the new development is on the Python side.  The **h2o4gpu** project is already supported by H2O.ai, and I think the R Consortium funding would be better used on open source projects without corporate backing.
