### ISSUE TITLE
h2o4gpu Deep Learning Algorithm

### ISSUE THREAD

**Issue by jtelleriar** [h2oai/h2o4gpu#535]
Are there any plans to support Deep Learning on h2o4gpu? Just as the original h2o package does?

Now that the "H2O.ai Deep Water Project" seems to have been discontinued this would be a very welcome feature.

**Comment by navdeep-G** [comment]
Hi @jtelleriar 

There is no plan at the moment. What ideas did you have in mind?

**Comment by jtelleriar** [comment]
Is there any "Deep Water" (https://github.com/h2oai/deepwater) code that could be re-used for h2o4gpu? Or even port the code from MXNet, Tensorflow, or the backends that "Deep Water" uses to h2o4gpu itself?

**Comment by mdymczyk** [comment]
@jtelleriar deepwater was just a frontend for TF and MXNet, for now we don't plan on implementing anything DL related as there are already good frameworks for that.
