### ISSUE TITLE
Clean up stage names in Jenkinsfiles

### ISSUE THREAD

**Issue by navdeep-G** [h2oai/h2o4gpu#556]
* Clearly state what each stage is doing to avoid confusion.
* This change should be purely cosmetic.

**Comment by terrytangyuan** [comment]
Main problem with the current CI is that the stages are not very clear. It would be good if the R tests are in a separate stage so it’s easier to check the logs

**Comment by navdeep-G** [comment]
@mdymczyk I think a change like this can be done once we reduce the # of Jenkinsfile's in the repo

**Comment by mdymczyk** [comment]
Closing in favor of #564
