### ISSUE TITLE
GitHub cannot infer project license 

### ISSUE THREAD

**Issue by mmalohlava** [h2oai/h2o4gpu#577]
Based on feedback from @st-pasha:

It seems like the GitHub has problem to figure out right license of the project. There is no license in project header:

![image](https://user-images.githubusercontent.com/597582/39214274-c3b0968c-47c8-11e8-8e66-eb2765828477.png)

You can compare it with https://github.com/h2oai/h2o-3 project header:
![image](https://user-images.githubusercontent.com/597582/39214620-f0e879f2-47c9-11e8-84a9-a509e19502f5.png)

**Comment by mdymczyk** [comment]
@mmalohlava any idea why GitHub is not recognizing it? I compared H2O-3's license file with H2O4GPU's file and it looked almost the same (sans copyright year). Might it be our `LICENSES` folder?
