### ISSUE TITLE
fix cuda detection

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#593]
When I relink /usr/local/cuda-8.0 -> /usr/local/cuda and do make build, I get the below.  My check correctly says it's cuda8, but CMake says cuda9.0 is detected.  I think I mentioned this already before.  I have to manually fix things.  How does the normal build work on jenkins that doesn't have this problem?

```
src/config2.mk:31: Compiling with Cuda8 or lower
Makefile:28: Compiling with Cuda8 or lower
echo ADD UPDATE SUBMODULE HERE
ADD UPDATE SUBMODULE HERE
mkdir -p build && \
cd build && \
cmake -DDEV_BUILD= -DNVML_LIB=/usr/lib/nvidia-384/libnvidia-ml.so ../ && \
make -j && \
cp _ch2o4gpu_*pu.so ../src/interface_c/ && \
cp ch2o4gpu_*pu.py ../src/interface_py/h2o4gpu/libs;
-- Building RELEASE compute capability version.
-- CUDA 9.0 detected, adding Volta compute capability (7.0).
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jon/h2o4gpu/build
```

**Comment by pseudotensor** [comment]
Is it because CMake is using my driver version to get some info?  That wouldn't be good, because one can have very high driver version but low cuda version and that's ok.

**Comment by mdymczyk** [comment]
Tested this on `dl14`:

```
src/config2.mk:31: Compiling with Cuda8 or lower
Makefile:28: Compiling with Cuda8 or lower
// logs
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "8.0")
```

Then changed to 9:

```
mateusz@mr-dl14:~/Dev/code/h2o4gpu$ sudo rm /usr/local/cuda
mateusz@mr-dl14:~/Dev/code/h2o4gpu$ sudo ln -s /usr/local/cuda-9.0 /usr/local/cuda
mateusz@mr-dl14:~/Dev/code/h2o4gpu$ rm -rf build/
mateusz@mr-dl14:~/Dev/code/h2o4gpu$ make cpp
// logs
src/config2.mk:27: Compiling with Cuda9 or higher
// logs
-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "8.0")
```

Do you have any CUDA related env variables set?

For docker this is a non issue since each docker has only 1 CUDA installed.

CMake also cannot get if from the driver, some machines we run this on don't have drivers (ppc ones).
