### ISSUE TITLE
Enable bleeding edge users to pin a particular historical commit (0.2.0.9999+master.42cf30e does not work)

### ISSUE THREAD

**Issue by mirekphd** [h2oai/h2o4gpu#601]
------------------------

### Environment 

Operating system:
#119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
Linux-4.4.0-96-generic-x86_64-with-debian-stretch-sid
CUDA Version: 8.0.61
CuDNN version: 6.0.21

Python version: 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)  [GCC 7.2.0]
Python version used by this container:
Python 3.6.4 :: Anaconda, Inc.
Conda version:
conda 4.5.3
Pip version:
pip 10.0.1 from /opt/conda/lib/python3.6/site-packages/pip (python 3.6)

H2O4GPU installed like this:
!wget --quiet https://s3.amazonaws.com/h2o-release/h2o4gpu/releases/bleeding-edge/ai/h2o/h2o4gpu/0.2-nccl-cuda8/h2o4gpu-0.2.0.9999-cp36-cp36m-linux_x86_64.whl
!pip install h2o4gpu-0.2.0.9999-cp36-cp36m-linux_x86_64.whl --no-cache-dir

Affected H2O4GPU version:

H2O4GPU:
Name: h2o4gpu
Version: 0.2.0.9999+master.42cf30e
Summary: H2O.ai GPU Edition
Home-page: http://h2o.ai
Author: H2O.ai, Inc.
Author-email: h2ostream@googlegroups.com
License: Apache v2.0
Location: /opt/conda/lib/python3.6/site-packages
Requires: pandas, scikit-learn, python-dateutil, tabulate, scipy, numpy, psutil, future, pytz, sklearn
Required-by: 

### Description

The above installation worked when the bleeding edge of H2O4GPU was 0.2.0.9999+master.55166b0, but does not work now, when the version was silently upgraded to 0.2.0.9999+master.42cf30e.

To reproduce:
```
import h2o4gpu as h2o4gpu
print(h2o4gpu.ElasticNetH2O)
```

Error message:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
__init__.pxd in numpy.import_array()

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-5-52d50ca8a000> in <module>()
     10 print(xgb.Booster)
     11 
---> 12 import h2o4gpu as h2o4gpu
     13 # print(h2o4gpu.ElasticNetH2O)
     14 

/opt/conda/lib/python3.6/site-packages/h2o4gpu/__init__.py in <module>()
     19     from .solvers.daal_solver.regression import Method as LinearMethod
     20 from .types import FunctionVector
---> 21 from .solvers.pogs import Pogs
     22 from .solvers.elastic_net import ElasticNet
     23 from .solvers.elastic_net import ElasticNetH2O

/opt/conda/lib/python3.6/site-packages/h2o4gpu/solvers/__init__.py in <module>()
      6 
      7 from ..solvers.pogs import Pogs
----> 8 from ..solvers.elastic_net import ElasticNetH2O
      9 from ..solvers.elastic_net import ElasticNet
     10 from ..solvers.logistic import LogisticRegression

/opt/conda/lib/python3.6/site-packages/h2o4gpu/solvers/elastic_net.py in <module>()
     13 import pandas as pd
     14 from tabulate import tabulate
---> 15 from h2o4gpu.linear_model import coordinate_descent as sk
     16 from ..solvers.utils import _setter
     17 

/opt/conda/lib/python3.6/site-packages/h2o4gpu/linear_model/__init__.py in <module>()
     10 # complete documentation.
     11 
---> 12 from .base import LinearRegressionSklearn
     13 
     14 from .bayes import BayesianRidgeSklearn, ARDRegression

/opt/conda/lib/python3.6/site-packages/h2o4gpu/linear_model/base.py in <module>()
     26 from ..externals import six
     27 from ..externals.joblib import Parallel, delayed
---> 28 from ..base import BaseEstimator, ClassifierMixin, RegressorMixin
     29 from ..utils import check_array, check_X_y, deprecated, as_float_array
     30 from ..utils.validation import FLOAT_DTYPES

/opt/conda/lib/python3.6/site-packages/h2o4gpu/base.py in <module>()
     10 from scipy import sparse
     11 from .externals import six
---> 12 from .utils.fixes import signature
     13 from . import __version__
     14 

/opt/conda/lib/python3.6/site-packages/h2o4gpu/utils/__init__.py in <module>()
      8 import warnings
      9 
---> 10 from .murmurhash import murmurhash3_32
     11 from .validation import (as_float_array,
     12                          assert_all_finite,

h2o4gpu/utils/murmurhash.pyx in init h2o4gpu.utils.murmurhash()

__init__.pxd in numpy.import_array()

ImportError: numpy.core.multiarray failed to import
```

### Issue and solution

The currently proposed build underlying the link to the bleeding edge H2O4GPU can change unpredictably, breaking functionality. You should enable bleeding edge users to pin a particular commit - you probably just need to add the subversion ("+master.<COMMIT_HASH>", e.g. to the download link and store all historical builds (not just the latest one) for download from Amazon.

**Comment by mdymczyk** [comment]
> The currently proposed build underlying the link to the bleeding edge H2O4GPU can change unpredictably, breaking functionality.

Yes, that's the whole idea behind bleeding edge builds. But I see your point, will try to push also whls with git hash in name so people can download.

**Comment by mirekphd** [comment]
Great to hear that build (commit) pinning will be available since ver. 0.2.2!

Regarding the problem with build 0.2.0.9999+master.42cf30e - I think this bug is an interaction of H2OGPU with Caffe's dependencies from Anaconda - try a conda install of Caffe-GPU and you should be able to reproduce it with any version of H24GPU:

```
RUN conda install -c anaconda caffe-gpu=1.0
```

In my case I confirm that removing this Caffe installation and (unwittingly...) switching to newest H2O4GPU build (0.2.0.9999+master.388d0f0) has repaired the probllem - your library loads correctly and elastic net solver uses GPU (circa 50%, as previously when it worked).
