### ISSUE TITLE
 xgboost is old version 0.60 or new one 0.71?

### ISSUE THREAD

**Issue by Sandy4321** [h2oai/h2o4gpu#606]
may you help understand where it is written what versions of software from other company you using, for example, xgboost is old version 0.60 or new one 0.71

Please do not use issues to ask questions. For questions use either [StackOverflow](https://stackoverflow.com/questions/tagged/h2o4gpu) (`h2o4gpu` tag) or [Gitter](https://gitter.im/h2oai/h2o4gpu?utm_source=share-link&utm_medium=link&utm_campaign=share-link).

GitHub issues are used for:

* Bug reporting.
* Feature/enhancement requests and discussion.

Before submitting a new issue please make sure a similar issue is not already present in the tracker.

Please make sure to fill out the form below as best as you can. This will help both you and us.

------------------------

### Environment (for bugs)

- **OS platform, distribution and version (e.g. Linux Ubuntu 16.04)**:
- **Installed from (source or binary)**:
- **Version**: 
- **Python version (optional)**:
- **CUDA/cuDNN version**:
- **GPU model (optional)**:
- **CPU model**:
- **RAM available**:

Please refer to google on how to obtain the above on your platform.

### Description

Describe the problem or enhancement/feature here as clearly and concisely as possible.

For bugs please provide an [MCVE](https://stackoverflow.com/help/mcve) and all the logs/source code you can. Large log and source code files should be attached separately instead of being pasted.

For how to write enhancements/feature requests please check our [CONTRIBUTING document](CONTRIBUTING.md#enhancements-and-feature-requests).

**Comment by mdymczyk** [comment]
For XGboost we have our own fork, which we try to keep as up-to-date with the original master as possible. You can find it here: https://github.com/h2oai/xgboost/tree/h2oai Currently our stable version has version 0.6, bleeding edge 0.71. The creator of the XGBoost GPU plugin is working at H2O (Rory) and our own fork has some additional bugfixes/features (not yet documented, though).

You can check which version of xgboost is installed with:

```
>>> import xgboost
>>> xgboost.__version__
```

**Comment by Sandy4321** [comment]
sorry I can not understand your answer
1
I use windows
but xgboost cannot be installed on windows for new version 0.7
 it is the reason why I want to use h2o
2
from your link
bleeding edge 0.71
, it is not clear how to install this  bleeding edge 0.71 based on h2o
3
may you give a clear answer
what is link how to install h2o on windows to have xgboost bleeding edge 0.71

**Comment by Sandy4321** [comment]
bleeding edge 0.71. 
looks good, how can I install H2O with bleeding edge 0.71. on windows computer
