### ISSUE TITLE
G++ 6.4 compilation failing

### ISSUE THREAD

**Issue by thirdwing** [h2oai/h2o4gpu#607]
Please do not use issues to ask questions. For questions use either [StackOverflow](https://stackoverflow.com/questions/tagged/h2o4gpu) (`h2o4gpu` tag) or [Gitter](https://gitter.im/h2oai/h2o4gpu?utm_source=share-link&utm_medium=link&utm_campaign=share-link).

GitHub issues are used for:

* Bug reporting.
* Feature/enhancement requests and discussion.

Before submitting a new issue please make sure a similar issue is not already present in the tracker.

Please make sure to fill out the form below as best as you can. This will help both you and us.

------------------------

### Environment (for bugs)

- **OS platform, distribution and version**: Ubuntu 18.04
- **Installed from**: source
- **Version** :  038c69c2560c37c5ce34d7f94dbd0b9011dabccd
- **Python version**: 3.6
- **CUDA/cuDNN version**: 9.1
- **GCC version**: 6.4
- **GPU model (optional)**: GTX 1060
- **CPU model**: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
- **RAM available**: 16 GB

Please refer to google on how to obtain the above on your platform.

### Description

Currently, in README, we claimed `NOTE: CUDA 9.1 is not currently compatible with H2O4GPU`.

And people might meet the following error when compiling with CUDA 9.1:

```
Error: Internal Compiler Error (codegen): "there was an error in verifying the lgenfe output!"
```

There is a workaround for this problem: removing `-std=c++11` from `CUDA_NVCC_FLAGS` (https://github.com/h2oai/h2o4gpu/blob/master/CMakeLists.txt#L118).

The default C++ standard used by GCC 6.4 should be C++14:

```
$ g++ --version
g++ (Ubuntu 6.4.0-17ubuntu1) 6.4.0 20180424
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ -dM -E -x c++  /dev/null | grep -F __cplusplus
#define __cplusplus 201402L
```

So `-std=c++11` is not necessary and it can cause some compiling problems with NVCC.

**Comment by mdymczyk** [comment]
Hey @thirdwing thanks for the input. Actually I tried compiling against CUDA 9.1 and it seems our rewrite to CMake fixed the issues and you can now compile against 9.1 without problems. We'll probably start publishing whls for 9.1 soonish.

As for gcc/g++ 6.x I tried it and seems to be failing, but not in nvcc because of std=c++1 but because of some code in our GLM implementation, so I'll rename this issue and hopefully we'll have a look at it in the future.

**Comment by mirekphd** [comment]
FYI, your have missed an entire subversion of CUDA, as there is already next one out, CUDA 9.2, stable on Ubuntu 16.04 and experimental on 18.04.

**Comment by mdymczyk** [comment]
@mirekphd yes we are aware of this, CUDA 9.1 had some backwards compatibility which we decided not to investigate as 9.2 was supposed to get released soon. Now it seems 9.1 to be working (i redid the build system, probably thats why) and I'll have a look at 9.2 this week.

**Comment by mdymczyk** [comment]
@thirdwing thanks, will try it out!
