### ISSUE TITLE
Redhat linux compatiblity

### ISSUE THREAD

**Issue by dockstreet** [h2oai/h2o4gpu#612]
Hi,

Can Red Hat Linux support be added besides Ubuntu? Or will it work currently without modification as long as CUDA 9.0 is installed. 

Am I mistaken or is CentOS supported already? I do see a docker file. Could that be leveraged or is that something else? From my understanding RHEL is fairly compatible with CentOS.

**Comment by mdymczyk** [comment]
@dockstreet the wheels we currently publish will only work with *nix systems with glibc 2.23+, which is hard to come by on rhel/centos, so they won't work there. You can build the project yourself on a centos machine or on any other using our centos docker, though.

We have a PR ready where we build all our whls on centos which should help but it will take some time before we merge it in https://github.com/h2oai/h2o4gpu/pull/564
