### ISSUE TITLE
Wheel file names should indicate which CUDA version they depend on

### ISSUE THREAD

**Issue by gitclem** [h2oai/h2o4gpu#623]
### Environment (for bugs)

- **OS platform:** Linux Ubuntu 16.04
- **Installed** from wheel binary
- **Version**:   h2o4gpu-0.2.0-cp36-cp36m-linux_x86_64.whl
- **Python version (optional)**: 3.6.0
- **CUDA/cuDNN version**: CUDA 8
- **GPU model (optional)**: 1080
- **CPU model**: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
- **RAM available**: 63GB CPU, 8G GPU

### Description
I downloaded the wrong wheel file and when I ran the code in the README, I got the msg: 

```
>>> import h2o4gpu
>>> import numpy as np
>>> X = np.array([[1.,1.], [1.,4.], [1.,0.]])
>>> model = h2o4gpu.KMeans(n_clusters=2,random_state=1234).fit(X)
Exception
libcudart.so.9.0: cannot open shared object file: No such file or directory
```

After a bit, I realized I had downloaded the wrong version of the wheel file.  However, I noticed that the wheel filename doesn't indicate for which CUDA is needed. as both versions have the exact same name:  `h2o4gpu-0.2.0-cp36-cp36m-linux_x86_64.whl`

Also, it would be nice if some error checking can occur during import to see if the right CUDA has been set up.

**Comment by mdymczyk** [comment]
@gitclem thanks! Totally agree, will try to add this asap. We probably will need this for uploads to PyPI anyway.

**Comment by pseudotensor** [comment]
The exception itself is pretty informative, but the long-term solution is to build cuda in statically, so closing this issue in favor of that one.
