### ISSUE TITLE
JIT forward compatibility

### ISSUE THREAD

**Issue by mdymczyk** [h2oai/h2o4gpu#628]
Our CMake should mimic XGBoost's improvements https://github.com/dmlc/xgboost/pull/3316 so CUDA8 builds can work on new cards/drivers (even if not compiled with sm70).

**Comment by Pscheidl** [comment]
Being solved in https://github.com/h2oai/xgboost/pull/45 ?

**Comment by mdymczyk** [comment]
@Pscheidl that's only for XGBoost. XGBoost and 4gpu have separate CMakeLists files so we'll have to duplicate that solution in 4gpu's CMakeList also (or just use XGBoost's CMake methods but still our CmakeLists needs an update).

**Comment by sh1ng** [comment]
was fixed in https://github.com/h2oai/h2o4gpu/pull/709
