### ISSUE TITLE
KMeans data quantization demo fails

### ISSUE THREAD

**Issue by mdymczyk** [h2oai/h2o4gpu#630]
The h2o4gpu subset part of the demo is failing, on a 2 GPU machine (dl14) the colors are way off and the whole image is divided into 4 parts which are scrambled. In 1GPU mode only the colors are way off. It works on the full dataset.

**Comment by sh1ng** [comment]
![download](https://user-images.githubusercontent.com/2821871/55327110-a65ee380-5489-11e9-8f7b-2d9c516f2be0.png)

**Comment by sh1ng** [comment]
![download (3)](https://user-images.githubusercontent.com/2821871/55440730-eec0f300-55a8-11e9-8887-277b019eaeb4.png)
![download (2)](https://user-images.githubusercontent.com/2821871/55440731-eec0f300-55a8-11e9-93a6-c16956f9d6ef.png)

**Comment by sh1ng** [comment]
Found one more issue https://github.com/h2oai/h2o4gpu/issues/748
