### ISSUE TITLE
Is PCA actually running correctly?

### ISSUE THREAD

**Issue by trivialfis** [h2oai/h2o4gpu#657]
For this line:
https://github.com/h2oai/h2o4gpu/blob/81e09028cb3b8a0c8bb121d35f6f433f5d8fb2c2/src/gpu/pca/pca.cu#L41

The single ":" is defining a tag for goto statement, and my compiler says the tag is never used, so I assume the actual purpose for this line of code is calling multiply function.

I don't know how to create tests for PCA. Maybe take a look? :(

**Comment by navdeep-G** [comment]
Seems like a mistake. I can fix tomorrow. Odd tests are passing though in Python.
