### ISSUE TITLE
error: ‘PyUnicode_AsUTF8’ was not declared in this scope

### ISSUE THREAD

**Issue by nasica88** [h2oai/h2o4gpu#658]
### Environment (for bugs)

- **OS platform, distribution and version : Redhat 7.5 ALT ppc64le
- Installed from (source or binary): from source 
- Version: 0.0.4
- Python version (optional): python 3.6 from Anaconda 5.0
- CUDA/cuDNN version: CUDA 9.2 cuDNN 7.1
- GPU model (optional): V100
- CPU model: POWER9
- RAM available: 512GB

### Description

I am trying to build h2o4gpu on Redhat 7.5 ppc64le with Anaconda3.   It keeps failing with the following error.   Can anyone suggest a solution, please ?

[bsyu@ING h2o4gpu]$ make fullinstall
...
make[3]: Entering directory `/home/bsyu/h2o4gpu/build'
[ 91%] Building CXX object CMakeFiles/gpuh2o4gpu.dir/src/common/logger.cpp.o
[ 91%] Building CXX object CMakeFiles/gpuh2o4gpu.dir/src/common/elastic_net_ptr.cpp.o
[ 91%] Building CXX object CMakeFiles/gpuh2o4gpu.dir/src/common/utils.cpp.o
[ 94%] Linking CXX static library libgpuh2o4gpu.a
make[3]: Leaving directory `/home/bsyu/h2o4gpu/build'
[ 94%] Built target gpuh2o4gpu
make[3]: Entering directory `/home/bsyu/h2o4gpu/build'
Scanning dependencies of target _ch2o4gpu_gpu
make[3]: Leaving directory `/home/bsyu/h2o4gpu/build'
make[3]: Entering directory `/home/bsyu/h2o4gpu/build'
[ 97%] Building CXX object CMakeFiles/_ch2o4gpu_gpu.dir/CMakeFiles/_ch2o4gpu_gpu.dir/ch2o4gpu_gpuPYTHON_wrap.cxx.o
/home/bsyu/h2o4gpu/build/CMakeFiles/_ch2o4gpu_gpu.dir/ch2o4gpu_gpuPYTHON_wrap.cxx: In function ‘PyObject* _wrap_get_gpu_info_c(PyObject*, PyObject*)’:
/home/bsyu/h2o4gpu/build/CMakeFiles/_ch2o4gpu_gpu.dir/ch2o4gpu_gpuPYTHON_wrap.cxx:11225:58: **error: ‘PyUnicode_AsUTF8’ was not declared in this scope**
         arg6[i] = PyUnicode_AsUTF8(PyList_GetItem(obj4,i));
                                                          ^
make[3]: *** [CMakeFiles/_ch2o4gpu_gpu.dir/CMakeFiles/_ch2o4gpu_gpu.dir/ch2o4gpu_gpuPYTHON_wrap.cxx.o] Error 1
make[3]: Leaving directory `/home/bsyu/h2o4gpu/build'
make[2]: *** [CMakeFiles/_ch2o4gpu_gpu.dir/all] Error 2
make[2]: Leaving directory `/home/bsyu/h2o4gpu/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/bsyu/h2o4gpu/build'
make: *** [cpp] Error 2

**Comment by nasica88** [comment]
I could finally solve this trouble by using gcc 7.2. which I had to build from source.

I also had to insert the following line these two files.

[bsyu@ING h2o4gpu]$ vi ./src/cpu/h2o4gpuglm.cpp  ./src/gpu/h2o4gpuglm.cu
...
#include <numeric>  # added


[bsyu@ING h2o4gpu]$ make fullinstall CC=/usr/local/gcc72/bin/gcc CXX=/usr/local/gcc72/bin/g++
...
Successfully installed h2o4gpu-0.2.0.9999+local.1dad27d.dirty
make[1]: Leaving directory `/home/bsyu/h2o4gpu/src/interface_py'
mkdir -p src/interface_py/dist/ppc64le-centos7-cuda9.2/ && mv src/interface_py/dist/*.whl src/interface_py/dist/ppc64le-centos7-cuda9.2/


[bsyu@ING h2o4gpu]$ find . -name "h2o4gpu-0.2.0*"
./src/interface_py/dist/h2o4gpu-0.2.0.9999+local.1dad27d.dirty.tar.gz
./src/interface_py/dist/ppc64le-centos7-cuda9.2/h2o4gpu-0.2.0.9999+local.1dad27d.dirty-cp36-cp36m-linux_ppc64le.whl

**Comment by pseudotensor** [comment]
@mateusz can you see if this can be incorporated into main build?  I guess caused by centos build?

**Comment by nasica88** [comment]
@mdymczyk  I omitted commenting that I had upgraded python version to 3.6.5 which was built on gcc 7.2.   Then I had the familiar error of 'undefined symbol: _gfortran_stop_numeric_f08'.  I installed gcc7.2 to resolve this new trouble.   My apology for the confusion.
