### ISSUE TITLE
conda package for h2o4gpu

### ISSUE THREAD

**Issue by jakirkham** [h2oai/h2o4gpu#667]
Would be great to have a `conda` package for `h2o4gpu`. Appears one was added for [`h2o`]( https://anaconda.org/h2oai/h2o ) recently.

**Comment by pseudotensor** [comment]
@hemenkapadia , can you clarify if the conda package you have created will be built for open-source h2o4gpu as well?  I think that's the goal, right?

**Comment by hemenkapadia** [comment]
Yes, it will.

**Comment by hemenkapadia** [comment]
PR #671 created to merge conda build recipe with master. Local conda package can be created using `make docker-build`till internal conda server is updated to release the build conda packages on h2oai conda channel.

**Comment by hemenkapadia** [comment]
Taking the strategy as implemented in caffe2 (https://anaconda.org/caffe2/caffe2/files) to provide cuda build variants for h2o4gpu. Assuming that package name will be self explanatory for a user installing it.

**Comment by hemenkapadia** [comment]
Work completed. Awaiting PR merge to master.

**Comment by hemenkapadia** [comment]
@jakirkham , yes once the PR is merged and a release build is run, the packages will be published to anaconda cloud too at https://anaconda.org/h2oai

**Comment by hemenkapadia** [comment]
h2o4gpu packages are now available in h2oai channel on anaconda cloud. https://anaconda.org/h2oai.

Closing the issue.
