### ISSUE TITLE
pip install h2o4gpu fails on Windows 10, 64-bit env

### ISSUE THREAD

**Issue by cpoptic** [h2oai/h2o4gpu#673]
------------------------

### Environment (for bugs)

- **OS platform, distribution and version (e.g. Linux Ubuntu 16.04)**:  Windows 10
- **Installed from (source or binary)**:
- **Version**: 
- **Python version (optional)**:  3.6.6
- **CUDA/cuDNN version**:  9.0/7.2
- **GPU model (optional)**:  nVidia Geforce 1070
- **CPU model**:  i7
- **RAM available**:  16GB

### Description
After cloning the h2o4gpu into my projects directory, 
```
cd D:\projects\h2oai\h2o4gpu
pip install h2o4gpu
```

Running pip install fails

> running install
> running build
> Traceback (most recent call last):
>   File "setup.py", line 125, in <module>
>     cmdclass={'bdist_wheel': bdist_wheel, 'build': H2O4GPUBuild, 'install': H2O4GPUInstall},
>   File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 140, in setup
>     return distutils.core.setup(**attrs)
>   File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
>     dist.run_commands()
>   File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "setup.py", line 62, in run
>     install.run(self)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 65, in run
>     orig.install.run(self)
>   File "C:\ProgramData\Anaconda3\lib\distutils\command\install.py", line 545, in run
>     self.run_command('build')
>   File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "setup.py", line 21, in run
>     EXT = ".dylib" if os.uname()[0] == "Darwin" else ".so"
> AttributeError: module 'os' has no attribute 'uname

**Comment by mdymczyk** [comment]
@cpoptic we don't support Windows.

**Comment by drag05** [comment]
Hello,

I wonder if there have been any developments to getting `h2o4gpu` on `Windows 10`.

Thank you!
