### ISSUE TITLE
Broken links to python wheels

### ISSUE THREAD

**Issue by mirekphd** [h2oai/h2o4gpu#685]
### Environment (for bugs)

- **OS platform**: linux 64-bit
- **Installed from (source or binary)**: binary
- **Version**: 0.3.0
- **Python version (optional)**: 3.6
- **CUDA/cuDNN version**: 8.0, 9.0, 9.2
- **GPU model (optional)**: any

### Description

Links to Python wheels of the recently released stable version (0.3.0) are broken - not just malformed or obsolete - the underlying files are missing on the server.

To reproduce:
- follow this link to version 0.3.0:
[0.3-nccl-cuda8/h2o4gpu-0.3.0-cp36-cp36m-linux_x86_64.whl](https://s3.amazonaws.com/h2o-release/h2o4gpu/releases/stable/ai/h2o/h2o4gpu/0.3-nccl-cuda8/h2o4gpu-0.3.0-cp36-cp36m-linux_x86_64.whl)

Expected behavior:
- follow this link to version 0.2.0:
[0.2-nccl-cuda8/h2o4gpu-0.2.0-cp36-cp36m-linux_x86_64.whl](https://s3.amazonaws.com/h2o-release/h2o4gpu/releases/stable/ai/h2o/h2o4gpu/0.2-nccl-cuda8/h2o4gpu-0.2.0-cp36-cp36m-linux_x86_64.whl)

Note: this bug applies to all 5 links in the[ "PIP install" section on the README page](https://github.com/h2oai/h2o4gpu/blob/master/README.md)

### PIP install 
Download the Python wheel file (For Python 3.6 on linux_x86_64):

  * Stable:
    * [CUDA8](https://s3.amazonaws.com/h2o-release/h2o4gpu/releases/stable/ai/h2o/h2o4gpu/0.3-nccl-cuda8/h2o4gpu-0.3.0-cp36-cp36m-linux_x86_64.whl)
    * [CUDA9](https://s3.amazonaws.com/h2o-release/h2o4gpu/releases/stable/ai/h2o/h2o4gpu/0.3-nccl-cuda9/h2o4gpu-0.3.0-cp36-cp36m-linux_x86_64.whl)
  * Bleeding edge (changes with every successful master branch build):
    * [CUDA8](https://s3.amazonaws.com/h2o-release/h2o4gpu/releases/bleeding-edge/ai/h2o/h2o4gpu/0.3-cuda8/h2o4gpu-0.3.0.9999-cp36-cp36m-linux_x86_64.whl)
    * [CUDA9.0](https://s3.amazonaws.com/h2o-release/h2o4gpu/releases/bleeding-edge/ai/h2o/h2o4gpu/0.3-cuda9/h2o4gpu-0.3.0.9999-cp36-cp36m-linux_x86_64.whl)
    * [CUDA9.2](https://s3.amazonaws.com/h2o-release/h2o4gpu/releases/bleeding-edge/ai/h2o/h2o4gpu/0.3-cuda92/h2o4gpu-0.3.0.9999-cp36-cp36m-linux_x86_64.whl)

**Comment by pseudotensor** [comment]
Thanks, fixed the README.
