### ISSUE TITLE
CUDA 10.0

### ISSUE THREAD

**Issue by joehoeller** [h2oai/h2o4gpu#746]
Is there a .whl URL for CUDA 10?

* Something like:
`pip install h204gpu-cuda10.whl`

If not, what would it take to support CUDA 10?

**Comment by sh1ng** [comment]
We're going to support CUDA 10 in the near future. The project works on it, but we need to update our infra and CI. BTW all versions are forward compatible, so you can use cuda92 installer.

**Comment by joehoeller** [comment]
The current .whl url doesnt work, can you post the correct one for `pip install` please?

**Comment by sh1ng** [comment]
What error do you get?

**Comment by nikolayvoronchikhin** [comment]
Hi @sh1ng , do you have ETA when it will be under the h2oai repo: https://anaconda.org/h2oai/repo

**Comment by nikolayvoronchikhin** [comment]
Hi @sh1ng , do you need any other details for this?

**Comment by sh1ng** [comment]
Hi @nikolayvoronchikhin  
We're continuously updating our infra to support cuda-10 plus working on Driver-less AI release. After that I can bump version(ETA 1 week).

**Comment by nikolayvoronchikhin** [comment]
Hi @sh1ng , how about  h2o4gpu-cuda10 ?

**Comment by sh1ng** [comment]
I've updated references in Readme. And I'm going to upload a new image to pypi this week.

**Comment by joehoeller** [comment]
Thanks guys!

**Comment by joehoeller** [comment]
As soon as its released, I'll come out with a CUDA enabled Docker container for it.

**Comment by joehoeller** [comment]
Does: 
`conda create -n h2o4gpuenv -c h2oai -c conda-forge h2o4gpu-cuda92
`
that work with CUDA10?

**Comment by nikolayvoronchikhin** [comment]
I still don't see  h2o4gpu-cuda10 in the repo: https://anaconda.org/h2oai/repo, so I'm assuming not yet.

**Comment by joehoeller** [comment]
So it seems to work in my container when I install from wheel, see Dockerfile, here:

https://github.com/joehoeller/drug-discovery-with-h2o4gpu

**Comment by sh1ng** [comment]
It was uploaded yesterday.

**Comment by joehoeller** [comment]
> It was uploaded yesterday.

Have a link?

**Comment by joehoeller** [comment]
@nikolayvoronchikhin  - > CUDA 10 Conda install link:
https://anaconda.org/h2oai/h2o4gpu-cuda10

**Comment by joehoeller** [comment]
My container that launches H2O4GPU with Jupyter, TensorRT etc is updated:
https://github.com/joehoeller/drug-discovery-with-h2o4gpu
