### ISSUE TITLE
Optimize memory usage of elastic net for multiple gpus  

### ISSUE THREAD

**Issue by sh1ng** [h2oai/h2o4gpu#763]
Original request from a customer #762 

Elastic net fails when tries to allocate memory on a first GPU while a few are available.   
https://github.com/h2oai/h2o4gpu/blob/master/src/gpu/matrix/matrix_dense.cu#L1945-L2016

To consider smarter usage of `upload_data` as it accepts device as a parameter.

**Comment by sh1ng** [comment]
Example notebook 
[Untitled (1).zip](https://github.com/h2oai/h2o4gpu/files/3108824/Untitled.1.zip)

**Comment by hemenkapadia** [comment]
Hi @sh1ng, is there a time frame to get this resolved ?

**Comment by sh1ng** [comment]
I hope to start in a week or two.

**Comment by hemenkapadia** [comment]
Hi @sh1ng , checking if you were able to make progress on this one. There is an open customer support ticket for it and we would like to get it resolved sooner.

**Comment by sh1ng** [comment]
I'm to work on it next week.

**Comment by sh1ng** [comment]
My original analysis was wrong.  
With current implementation every GPU has to have it's own copy of whole data-set to utilize data parallelism,  i.e. every GPU processes part of `alpha/lambda` parameters, but algorithm itself is not parallelised to multiple GPUs. 

Need a bit of more analysis to understand how(if) feasible it is. 
 cc @pseudotensor

**Comment by sh1ng** [comment]
We decided to use xgboost for linear models. At this point it scales enough and I'm able to handle data set that fails with `ElasticNet`.

snippet
```
param = {'objective': 'reg:squarederror',
         'booster': 'gblinear',
         'updater': 'gpu_coord_descent',
         'n_gpus': -1,
         }

dtrain = xgb.DMatrix(x, label=y)
```   

parameter `gpu_coord_descent` is not documented yet.
