### ISSUE TITLE
kmeans build error: namespace "thrust" has no member "device_malloc_allocator" 

### ISSUE THREAD

**Issue by Msabih** [h2oai/h2o4gpu#764]
Hi,

I am trying to build h2o4gpu on gcc7, cmake 3.12, cuda-10.1. During the cmake build process, I got this error

`h2o4gpu/src/gpu/kmeans/kmeans_labels.h(102): error: namespace "thrust" has no member "device_malloc_allocator"` 

Any idea why this error is coming ?

**Comment by sh1ng** [comment]
We a not going to support CUDA 10.1 https://github.com/dmlc/xgboost/issues/4264
Looks like a minor issue. Could you verify that `#include <device_malloc_allocator.h>` fix the issue? https://thrust.github.io/doc/classthrust_1_1device__malloc__allocator.html

**Comment by Msabih** [comment]
> We a not going to support CUDA 10.1 [dmlc/xgboost#4264](https://github.com/dmlc/xgboost/issues/4264)
> Looks like a minor issue. Could you verify that `#include <device_malloc_allocator.h>` fix the issue? https://thrust.github.io/doc/classthrust_1_1device__malloc__allocator.html

I know that CUDA 10.1 is not supported, I was just wondering if with minor tweaking it could be built, the build goes upto more than 50% but stucks.

I tried your solution, there is one more error 



`/h2o4gpu/src/gpu/kmeans/kmeans_h2o4gpu.h(120): error: no instance of overloaded function "kmeans::detail::memcpy" matches the argument list  `

**Comment by sh1ng** [comment]
fixed
