### ISSUE TITLE
Installation for Jetson Nano .whl is not working

### ISSUE THREAD

**Issue by dmcgoldrick** [h2oai/h2o4gpu#769]
Hello --

Thanks everyone! I am trying to install h2o4gpu on Jetson Nano 

Here is my kernel
nano@mcgoldphd-desktop:/opt/h2oai$ uname -a
Linux mcgoldphd-desktop 4.9.140-tegra #2 SMP PREEMPT Wed May 22 19:42:16 PDT 2019 aarch64 aarch64 aarch64 GNU/Linux

This is the Ubuntu release on it:
nano@mcgoldphd-desktop:/opt/h2oai$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
it is failing at :
pip install h2o4gpu-0.3.2-cp36-cp36m-linux_x86_64.whl
with :h2o4gpu-0.3.2-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.

is this a bug or is this code wheel not available for arm64

and no conda please can this work with pip python/3.6.+

**Comment by sh1ng** [comment]
We don't support `arm` architecture for now.
