### ISSUE TITLE
Improvements to glm (based upon recent suggestions for h2o-3 glm)

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#78]
Several requests and questions on h2o.glm features and solutions
Hi, H2O colleagues. Hope you all are well.

I am writing this message to summarize some of the feedbacks and feature requests that came up from one of my project in real world. First let me just say H2O's glm model, (or gbm and other models in H2O family) is second to none in terms of cpu and memory utilization efficiency. Also, even though a lot of emphasis nowadays are on neural network algorithms, for majority of the real world, large data set problems, linear models are still the most appropriate choices. So please keep maintaining and improving your great h2o.glm() implementations.

My project/problem is a project on a pretty large data set. The full dataset can be upwards of 100GB+. In the modeling stage, I mostly use R. Our production and end application platform is on Spark. However, currently in the modeling stage (training and cross-validation) I am just using a very large instance of AWS. The set of models I built are both for regression and classification problems on the dataset. I am currently only use linear models.

Here are a list of feature requests and problems that came up during the project. I am list them in what I think is the order of difficulty to implement:

Identity link function for h2o.glm classification model: Currently, in h2o.glm(), for a classification problem, a link function of identity is not allowed. This makes sense as for classification problem the output is probabilities which are bounded. And a linear output doesn't guarantee the 0-1 bound. However, in my case there is a clear use case for this. Because the target probabilities can be seen clearly have some linear relation with some variables. In reality, if I specify the problem as regression and fit the 1 or 0 outcomes, the resulted models are pretty much the same as a classification glm with identity link function. However, using the regression model many of the classification model metrics are not generated. I can generate these metrics on the R side. But as we will discuss for large data set, moving data back and forth, is not simple for H2O. Just as a reference point, the R default glm() model accept identity as a link function. For the classification lrm() model in rms package, identity link function is not accepted, only logistic function is accepted.

Interaction terms between numeric variables and categorical variables: Currently h2o.interaction only accept categorical variables. There are plenty of use cases for interaction between numeric fields and categorical variables. I currently can accomplish this with my own code: either in R, which increase the size of the data and make the pass data between R and H2O much more slower, or in code that create and manipulate H2O data frames and columns. However, it would be nice if h2o.interaction can handle one of the variable been numerical field.

Support for Restricted Cubic Spline Fit: For part of my problem and for many real work problems especially in finance, spline terms with linear models can sometimes do better job than some of the more complicated and more modern machine learning models, like tree models. As it forces a continuous relationship between different data points along some variables. Currently I use the R package rms, its classification model lrm and regression ols supports a couple of spline fitting models. However, rms is single threaded and is a memory hog when using large number of categorical variables and interactions. So I have to design my models into multi-stage and use rms model on a subset of data to generate a first stage model and use H2O on the second stage. If H2O's h2o.glm or H2O in general can provide some function to generate the spline terms (like h2o.interaction did for interactions), that will be really helpful. Currently I could try to generate the spline terms in R and push them to H2O. However, this have a couple of problems: a. Generate spline terms on my own may generate un-foreseen bugs in some edge cases. b. Generate spline terms in R increased the data size significantly. Hard to move the data back and forth. The resulted data are pretty sparse (with many zero fields). So once in H2O, H2O handles it very well. And H2O model fitting is pretty fast. c. It is hard to experiment and change the spline settings if we are transferring the data back and forth. So if H2O can provide the functions to generate spline terms in side of H2O, (cubic spline, or any other spline fitting model) that would be really helpful. And I think it could be a very welcome feature.

Output for PMML for model prediction portability: I know that H2O output POJO file for H2O model prediction function. However a couple of problem with that. It is still not portable enough. For example I can't re-load the POJO into R and call the POJO function to do the prediction on my data set and compare with original model output in case of problem/bug or collect statistics and generate charts standing alone without the original model. There is a project of JPMML library and there is a R package called r2pmml that is built on top of JPMML library. JPMML is in JAVA and since H2O already generate POJO file, shouldn't it be possible to write a wrapper around POJO to work in JPMML. I have contacted r2pmml author about pmml support for rms models. May be H2O can work with him to put H2O support for pmml support for H2O models? It should be great help for many real world projects.

Data transfer between R and H2O: I guess it is well-known that the data transfer between R and H2O is very slow. The fastest way to transfer data between R and H2O is using data.table's fwrite and H2O's importfile. This is somewhat acceptable for the data set that we transfer once. And we do many train->validate->changing parameters/models cycles. However, after any one model is trained and predictions are generated, not all metrics and statistics for some specific problem are generated in H2O. So many times we need to transfer the predictions back to R to do some analysis and transfer the results back. However, for a very large data set with hundreds millions of rows, even transfer the predictions back R is very slow. So if we are forced to write out the predictions to csv file ON DISK and then read back into R. This slows things down significantly. So even though H2O training is very fast, but if I have to transfer the predictions back to R through csv files, and run the intermediate analysis in R. Then each train->evaluation cycle becomes much longer and the advantage H2O over those single threaded models almost disappeared. Is there plan to provide faster data transfer between R and H2O? It should be possible, as data.table's fread and fwrite is blazing fast. And h2o.importFile is very fast. Can't we do the fwrite and h2o.importFile cycle in memory instead of on disk? Writing to disk on a AWS instance is very slow?

Anyway, these are all my feature requests/feedbacks so far. It becomes very long. Hopefully it provides some useful feedbacks. Looking forward to hearing from you. Thanks for your patience.

Best regards.

Wei

**Comment by navdeep-G** [comment]
Closing for xgb glm
