### ISSUE TITLE
Consider ARIMA implementation on GPU 

### ISSUE THREAD

**Issue by sh1ng** [h2oai/h2o4gpu#787]
Even a good CPU implementation would be beneficial, even sklearn decided to not implement it. https://github.com/scikit-learn/scikit-learn/pull/6029

**Comment by mardgui** [comment]
Why has this issue been closed? Has it been implemented or was it aborted?

**Comment by sh1ng** [comment]
https://github.com/h2oai/h2o4gpu/pull/797
