### ISSUE TITLE
When will Ubuntu 18.04.02 be supported?

### ISSUE THREAD

**Issue by chriseal** [h2oai/h2o4gpu#788]
Taylor Marrison Customer Engagement at h2o.ai sent me here. Will this repository work with Ubuntu 18.04.02? The highest supported CUDA version, 10.0, goes up to Ubuntu 18.04.01.  If not, when will 18.04.02 be supported?

I'm considering purchasing a [Lambdalabs Tensorbook](https://lambdalabs.com/deep-learning/laptops/tensorbook) that ships with 18.04.02 at the time of this writing, and would appreciate any insights.

**Comment by sh1ng** [comment]
It's already supported.
CUDA are backward compatible https://docs.nvidia.com/deploy/cuda-compatibility/ we no need to create a separate binary package for every CUDA release(while it may give some improvements and features), but we're going to support CUDA 10.1 in a near future.

**Comment by sh1ng** [comment]
BTW I'm using Ubuntu 18.04.2 LTS on my machine.

**Comment by chriseal** [comment]
Thank you @sh1ng ! So if I'm understanding this correctly, if i get a computer with Ubuntu 18.04.02 and CUDA 10.1, the h2o4gpu software should work since it already does for CUDA 10.0 / Ubuntu 18.04.01, correct?

**Comment by monk1337** [comment]
@chriseal Did you find the solution? I am using the same configuration GPU.

**Comment by chriseal** [comment]
I did get it to work on my machine @monk1337
