### ISSUE TITLE
.whl "not supported on this platform" when installing in python 3.6.8 conda virtual environment

### ISSUE THREAD

**Issue by chriseal** [h2oai/h2o4gpu#793]
My steps were:
```
conda create -n foGPU python=3.6.8 anaconda
conda activate foGPU
pip install ~/Downloads/h2o4gpu-0.3.2-cp36-cp36m-linux_ppc64le.whl
```

And the error message was:
```
ERROR: h2o4gpu-0.3.2-cp36-cp36m-linux_ppc64le.whl is not a supported wheel on this platform.
```

Could I be using the wrong Python version? 

Thanks for your help. Running on Ubuntu 18.04.02

**Comment by chriseal** [comment]
I think I solved this by running `conda create -n h2o4gpuenv -c h2oai -c conda-forge h2o4gpu-cuda10`, which currently isn't mentioned in the README. Maybe someone could update the README?

Also, when I ran the quick check, I got:

```
import h2o4gpu
import numpy as np

X = np.array([[1.,1.], [1.,4.], [1.,0.]])
model = h2o4gpu.KMeans(n_clusters=2,random_state=1234).fit(X)
model.cluster_centers_

## -- End pasted text --
Out[3]: 
array([[1. , 0.5],
       [1. , 4. ]])
```

which is different than what's in the README

**Comment by sh1ng** [comment]
You are trying to install [ppc64](https://en.wikipedia.org/wiki/Ppc64) version
