### ISSUE TITLE
PIP Install of Python Wheels fails for CUDA 10.1

### ISSUE THREAD

**Issue by cetoh** [h2oai/h2o4gpu#804]
The current lastest stable release in the CUDA 10 link seems to be 0.3.2 however the linux pip-install indicates it is 0.3.0. It should be noted that this version also does not seem to work.

Download the Python wheel file (For Python 3.6):

    Stable:
        CUDA9.0 - linux_x86_64
        CUDA10 - linux_x86_64
        CUDA9.0 - linux_ppc64le
        CUDA10 - linux_ppc64le
    Bleeding edge (changes with every successful master branch build):
        CUDA10.0 - linux_x86_64
        CUDA10.0 - linux_ppc64le

Start a fresh pyenv or virtualenv session.

Install the Python wheel file. NOTE: If you don't use a fresh environment, this will overwrite your py3nvml and xgboost installations to use our validated versions.

pip install h2o4gpu-0.3.0-cp36-cp36m-linux_x86_64.whl

**Comment by cetoh** [comment]
Following Linux Error is thrown:

ERROR: h2o4gpu-0.3.2-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform

**Comment by sh1ng** [comment]
What linux distributive do you use?

**Comment by sh1ng** [comment]
And Python version?

**Comment by cetoh** [comment]
`python -m pip install h2o4gpu
Collecting h2o4gpu
  ERROR: Could not find a version that satisfies the requirement h2o4gpu (from versions: none)
ERROR: No matching distribution found for h2o4gpu

python --version
Python 3.7.4

hostnamectl
Static hostname: brodyserver
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: 1118f9219be1442887bd33cfb6286293
           Boot ID: c920c6b4ba754d93afc73281c6bd4ea9
  Operating System: Ubuntu 18.04.3 LTS
            Kernel: Linux 5.0.0-32-generic
      Architecture: x86-64

`

**Comment by sh1ng** [comment]
You need to use python 3.6.

https://github.com/h2oai/h2o4gpu/issues/808
